### ISSUE TITLE
Getting started recommends pre-2018 aliasing

### ISSUE THREAD

**Issue by mark-summerfield** [gabdube/native-windows-gui#100]
In the Getting Started section it says to use:
```rust
extern crate native_windows_gui as nwg;
extern crate native_windows_derive as nwd;
```
But this can be avoided by doing this in `Cargo.toml`:
```
[dependencies]
nwg = {version = "^1.0.1", package = "native-windows-gui"}
nwd = {version = "^1.0.0", package = "native-windows-derive"}
```
Or at least this ought to be the solution, but in fact it doesn't work (I think due to the macros).

**Comment by gabdube** [comment]
I added a note in the readme for this
