### ISSUE TITLE
How to bring a window to the front?

### ISSUE THREAD

**Issue by mark-summerfield** [gabdube/native-windows-gui#102]
You can kind-of get the effect of a modal dialog by doing this:
```rust
fn on_some_event(&self) {
    self.window.set_enabled(false);
    nwg::simple_message(...
    self.window.set_enabled(true);
    // how to bring self.window to the front?
}
```
However after the message box is closed the main window ends up behind all the other application windows and I can't find an NWG API for bringing it to the front again.

**Comment by gabdube** [comment]
`self.window.set_focus` should do the trick

**Comment by mark-summerfield** [comment]
Yes it does, thank you.
