### ISSUE TITLE
"cargo run --example dataview_d" panic, error code: 2

### ISSUE THREAD

**Issue by xBINj** [gabdube/native-windows-gui#108]
my enviroment:
OS: Windows 10 version 1909 (18363.959)
Rust ver: 1.45.1

cargo run --example dataview_d panic info:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResourceCreationError("Failed to create image from source \'./test_rc/cog.ico\' ")', native-windows-gui\examples\dataview_d.rs:57:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\dataview_d.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)

I debug the codes, it panic in resources_helper.rs  codes:
`let mut handle = LoadImageW(ptr::null_mut(), filepath.as_ptr(), image_type, width as i32, height as i32, LR_LOADFROMFILE);
    if handle.is_null() {
        let (code, _) = get_system_error();
        if code == 2 && !strict {`
handle is null, and the error code is 2, message: Cannot find the file", 
but the cog.ico file exists, and the parameters used in LoadImageW is correct also.
can help tell me why? tks

**Comment by gabdube** [comment]
Did you call `cd .\native-windows-gui\` before running the example?

**Comment by xBINj** [comment]
> Did you call `cd .\native-windows-gui\` before running the example?

tks very much. problem is resolved.
oh, my mistake. I call it in the root directory, not in native-windows-gui.
tks again.
