### ISSUE TITLE
Selection issue in ListView

### ISSUE THREAD

**Issue by aleksey-r** [gabdube/native-windows-gui#110]
After calling the "select_item" method, the item is not visually selected in the ListView. 
```
let dv = &self.data_view;
dv.select_item(0, true);
```

**Comment by gabdube** [comment]
Might just need to redraw the control in the method. I'll look into it.

**Comment by gabdube** [comment]
Turns out I was wrong. ListView has now a flag ALWAYS_SHOW_SELECTION (on by default) to always show the selected item(s) even if the control is not currently in focus. Also decided to do a 1.0.3 release, yay!
