### ISSUE TITLE
How to get the parent node of a TreeView item?

### ISSUE THREAD

**Issue by chn-cutelotus** [gabdube/native-windows-gui#111]
Thanks.

**Comment by gabdube** [comment]
Oops. Forgot to add a method for this. Give me 5 minutes

**Comment by gabdube** [comment]
Fixed! Just point to the latest commit in `master` to get the new feature.

Here's an example:

```rust
let parent = tree.parent(&item).unwrap();
println!("{:?}", tree.item_text(&parent));
```

**Comment by chn-cutelotus** [comment]
That's wonderful. Especially your efficiency.
Yet, another problem turned out to be: how to get the level of selected item?

**Comment by gabdube** [comment]
To find the level you have to iterate over the parents. Here's an example
```rust
fn get_item_level(tree: &nwg::TreeView, mut item: nwg::TreeItem) -> u32 {
    let mut level = 0;
    while let Some(i) = tree.parent(&item) {
        item = i;
        level += 1;
    }

    level
}
```

**Comment by chn-cutelotus** [comment]
Thanks a lot. I got it.
