### ISSUE TITLE
How to use customized member variables ?

### ISSUE THREAD

**Issue by chn-cutelotus** [gabdube/native-windows-gui#112]
Hello sir. I'm coming again. Here is a new problem. I add some member variables to the window. But the value  can't be changed anywhere.
====================================================================
#[derive(Default, NwgUi)]
pub struct TreeViewApp {
    #[nwg_control(size: (600, 350), position: (300, 300), title: "section steel viewer")]
    #[nwg_events(OnWindowClose: [TreeViewApp::exit], OnInit: [TreeViewApp::load_data])]
    window: Window,
...
    profiles:HashMap<String, Vec<ProfileProperty>>    // customized variable
}

impl TreeViewApp {
    fn load_data(&self) {
        ...
        self.profiles.insert(  format!( // error occurs as below
                                            "{}|{}|{}",
                                            &profile_class, sheetname, profile_name
                                        ),
                                        profile_properties,
        );
    }
====================================================================
error:
^^^^^^^^^^^^^ `self` is a `&` reference, so the data it refers to cannot be borrowed as mutable
I tried to change function "load_data" as:
fn load_data(&self) { ... }
It still doesn't work.
How to change the value of member variable "profiles" ?
Thanks in advance.

**Comment by gabdube** [comment]
You have to wrap `profiles` inside a `RefCell`, so `profiles: RefCell<HashMap<String, Vec>>`. See https://doc.rust-lang.org/std/cell/index.html and https://doc.rust-lang.org/book/ch15-05-interior-mutability.html

The ui data must be immutable by default because it is shared Windows and your app. Interior mutability fixes this

**Comment by chn-cutelotus** [comment]
I see. Thanks for your kind answer.

**Comment by gabdube** [comment]
always happy to help
