### ISSUE TITLE
About item selection in TreeView

### ISSUE THREAD

**Issue by chn-cutelotus** [gabdube/native-windows-gui#113]
Hello sir. I always have questions. It seems that the program controlled item selection in TreeView  is invalid unless the TreeView is focused. And another problem is , the previous selection is not cleared when I try to select new items. How to tackle these two problems? Thanks for your coming help.

**Comment by gabdube** [comment]
Might be a similar issue to https://github.com/gabdube/native-windows-gui/issues/110 ? Tree view has a similar flag `TVS_SHOWSELALWAYS` . I'll look into it

**Comment by chn-cutelotus** [comment]
TVS_SHOWSELALWAYS is no available by now.

**Comment by gabdube** [comment]
Should be fixed in the lastest commit. Also `1.0.4` will be published later today.

**Comment by chn-cutelotus** [comment]
Thanks. But how to deselect the items in order to select a new one?

**Comment by gabdube** [comment]
oh I forgot this one.  I'm on it

**Comment by chn-cutelotus** [comment]
Still unsolved?

**Comment by gabdube** [comment]
You can now use `treeview.unselect_item(&item)` to unselect an item. It's on master and will be published in the next release

example:
```
let last = self.tree_view.selected_item().unwrap();
let new = self.tree_view.root().unwrap();
self.tree_view.select_item(&new);
self.tree_view.unselect_item(&last);
```

**Comment by chn-cutelotus** [comment]
Manually selected items can be unselected by the above method while program selected ones can not?

**Comment by gabdube** [comment]
Any item can be unselected with this method. Internally there's a "selected" flag for each tree item. This method just removes it.

**Comment by chn-cutelotus** [comment]
I found the problem. Program selected items can not get by method **selected_item()**
=========================================================
self.tree_view.select_item(someitem);
let selected_item=self.tree_view.selected_item(); // variable **selected_item** got None

**Comment by gabdube** [comment]
should be fixed now sorry for the wait :)
