### ISSUE TITLE
embed icons in treeview example

### ISSUE THREAD

**Issue by qtablesheets** [gabdube/native-windows-gui#117]
Hello,
trying to embed icon resources into the treeview example.
It compiles and runs, but the icons added to treeview's ImageList are not displayed, default windows icons are shown instead.
The returned indices are 0, 2 instead of the expected 0, 1.
Did I miss something?
Thank you.

from main.rc:

let em = &self.embed;

self.window.set_icon(em.icon_str("LOVE").as_ref()); **//works**

let i1 = icons.add_icon(em.icon_str("COG").as_ref().unwrap());
let i2 = icons.add_icon(em.icon_str("LOVE").as_ref().unwrap());
println!("{}, {}", i1, i2); **// does not work, indices 0 and 2 are returned, windows default icons are displayed**

// let i1 = icons.add_icon_from_filename("./test_rc/cog.ico").unwrap();
// let i2 = icons.add_icon_from_filename("./test_rc/love.ico").unwrap();
// println!("{}, {}", i1, i2); **// works, indices 0 and 1 are returned, cog.ico and love.ico are displayed**

treeview.rc:

#define RT_MANIFEST 24
1 RT_MANIFEST "treeview.exe.manifest"
MAINICON ICON "./test_rc/love.ico"
LOVE ICON "./test_rc/love.ico"
COG ICON "./test_rc/cog.ico"

**Comment by gabdube** [comment]
I don't see anything wrong with your example. I'll look into it.

For now you can enable `image-decoder` (it is by default, unless you have `default-features=false` in cargo) and try to define your resources as images:

```
LOVE IMAGE "./test_rc/love.ico"
COG IMAGE "./test_rc/cog.ico"
```

and load the image this way

```
icons.add_bitmap(embed.image_str("COG").as_ref().unwrap());
icons.add_bitmap(embed.image_str("LOVE").as_ref().unwrap());
```

**Comment by qtablesheets** [comment]
Thank you for looking into this. However, it is no showstopper at the moment.
The workaround did show the same default icons in treeview.

![image](https://user-images.githubusercontent.com/48253418/92695082-3e801e00-f348-11ea-9312-bf99aeee96d1.png)

**Comment by gabdube** [comment]
ohhhh that's because the icon is not resized when loaded from the embed resource and windows being windows just deal with it by handling the icon as two different icon. That's why selecting an item gives you the other side of the cog.

Now resizing an icon from an embed resource looks tricky, but I'll see what I can do

**Comment by gabdube** [comment]
Fixed!

You can now specify the size when loading from an embedded source
```
icons.add_icon(em.icon_str("COG", Some((16, 16))).as_ref().unwrap());
icons.add_icon(em.icon_str("LOVE", Some((16, 16))).as_ref().unwrap());
```

**Comment by qtablesheets** [comment]
Thank you, works fine now.
