### ISSUE TITLE
Use embedded / generated icons from &[u8]

### ISSUE THREAD

**Issue by nicolasbauw** [gabdube/native-windows-gui#118]
Hi,

I have a question about icons (systray in my case)
I've looked at the docs, examples, tried some things, but I can't figure how to use icons from a &[u8].
I do this way to embed icons with include_bytes! or generate icons with a function before using them.
I've seen a source_bin function, but I don't find the way to use it.

My last try:

```
pub struct SystemTray {
    #[nwg_control]
    window: nwg::MessageWindow,

    proxy_on: nwg::Icon,
    proxy_off: nwg::Icon,
...
```

```
fn load_icon(data: &[u8]) -> nwg::Icon {
    let mut icon = nwg::Icon::default();

    nwg::Icon::builder()
        .source_bin(Some(data))
        .strict(true)
        .build(&mut icon)
        .unwrap();

    icon
}
```

```
fn main() -> Result<(), Box<dyn Error>> {
    let _enabled_icon = include_bytes!("../assets/check-mark-16.ico");
    let disabled_icon = include_bytes!("../assets/x-mark-16.ico");
...
nwg::init()?;
    let ui = SystemTray::build_ui(Default::default())?;
    ui.proxy_off = load_icon(disabled_icon);
...
```

But seems I can't do that this way:

```
error[E0594]: cannot assign to data in a dereference of `system_tray_ui::SystemTrayUi`
   --> src\main.rs:105:5
    |
105 |     ui.proxy_off = load_icon(disabled_icon);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot assign
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `system_tray_ui::SystemTrayUi`
```

Looks like I can't modify the icon directly in the struct.
What do I not understand / doing bad ?
What's the recommended way to do that ?

**Comment by gabdube** [comment]
Right now there's a problem with icons and you can't load them from binary sources. That's on the top of my TODO list for this weekend. That said, here's how it would work

Native-windows derive doesn't generate the boilerplate for `DerefMut` because `SystemTray` is behind a RC internally.  Basically, as soon as you call `build_ui`, your ui data is set in stone and the only way to change it is to use interior mutability (ex: RefCell). 

That said, you're free to load your data before calling build_ui. So, for example:

```
fn main() -> Result<(), Box<dyn Error>> {
    let enabled_icon = include_bytes!("../assets/check-mark-16.ico");
    let disabled_icon = include_bytes!("../assets/x-mark-16.ico");

    let mut ui_data:  SystemTray = Default::default();
    ui_data.proxy_on = load_icon(enabled_icon);
    ui_data.proxy_off = load_icon(disabled_icon);
    // Any other data initialization

    let ui = SystemTray::build_ui(Default::default())?;
   
    nwg::dispatch_thread_events();
}
```

**Comment by gabdube** [comment]
Fixed!

I forgot to mention it but you can also load the icon directly from the macro using

```rust
const EMBED: &[u8] = include_bytes!("../test_rc/love.ico");
pub struct SystemTray {
#[nwg_resource(source_bin: Some(EMBED))]
icon: nwg::Icon,
}
```

Please reopen this issue if there's still a problem.

**Comment by nicolasbauw** [comment]
Thanks for your quick responses.
I've pulled the repo and had two tries.

First method:
```
const ENABLED_ICON: &[u8] = include_bytes!("../assets/check-mark-16.ico");
const DISABLED_ICON: &[u8] = include_bytes!("../assets/x-mark-16.ico");
const UNKNOWN_ICON: &[u8] = include_bytes!("../assets/question-mark-16.ico");
...
    #[nwg_resource(source_bin: Some(ENABLED_ICON))]
    proxy_on: nwg::Icon,

    #[nwg_resource(source_bin: Some(DISABLED_ICON))]
    proxy_off: nwg::Icon,

    #[nwg_resource(source_bin: Some(UNKNOWN_ICON))]
    proxy_unkn: nwg::Icon,
...
```
gave me
```
thread 'main' panicked at 'Icon required. TODO ERR', C:\Users\nbauw\Dev\native-windows-gui\native-windows-gui\src\controls\tray_notification.rs:369:21
```

Second method with the same load_icon function than above:
```
    let enabled_icon = include_bytes!("../assets/check-mark-16.ico");
    let disabled_icon = include_bytes!("../assets/x-mark-16.ico");
    let unknown_icon = include_bytes!("../assets/question-mark-16.ico");
    let mut ui_data:  SystemTray = Default::default();
    ui_data.proxy_on = load_icon(enabled_icon)?;
    ui_data.proxy_off = load_icon(disabled_icon)?;
    ui_data.proxy_unkn = load_icon(unknown_icon)?;

    // Building the systray
    nwg::init()?;
    let ui = SystemTray::build_ui(Default::default())?;
```
gave me
```
Error: ResourceCreationError("Failed to create a image factory")
```

The version with icons loading from files still works.
(problematic complete source [here](https://github.com/nicolasbauw/proxytoggle_systray_rs/blob/embed/src/main.rs)).

NOTE : I can't reopen the issue.

**Comment by gabdube** [comment]
The first error happens because the system tray object requires an icon. This error message really sucks and I'll update it right away.

```rust
#[nwg_control(icon: Some(&data.icon)))]  // <- Required
 tray: nwg::TrayNotification, 
```

Also, make sure to call `nwg::init()?;` before every other NWG call (including load_icon). That's probably why the second example don't work.

**Comment by nicolasbauw** [comment]
Thanks again. Originally I removed the icon to set it myself at startup. I put it back, now the first method works.
I still did not manage to make the second method work. That's not too much a problem, because if I want to update icons dynamically (that's another repo), I'll have to get into that RefCell thing (never worked with that until now), or alternatively create an update method in the struct, giving the icon data as argument.

Thank you very much for your library and your support.
