### ISSUE TITLE
Placeholder Text for TextInput

### ISSUE THREAD

**Issue by morshcode** [gabdube/native-windows-gui#119]
Hey,

Started using this fantastic library today and I'm missing a few things that would be neat.
One of them is being able to set a placeholder text for text inputs.

I believe it can be accomplished with:

> https://docs.microsoft.com/en-us/windows/win32/controls/em-setcuebanner

But I'm not sure if it's viable to use it because of the note:

> To use this API, you must provide a manifest specifying Comclt32.dll version 6.0

What do you think?

Thanks!

**Comment by gabdube** [comment]
If I remember correctly there was a problem when I tried to implement it the first time, but I don't really remember so I'll try again.

**Comment by morshcode** [comment]
I did a quick and dirty attempt of implementing this and it seems to work, the only issue I ran into was that `EM_SETCUEBANNER` was not defined anywhere that I could see, so I used a constant `0x1501`. Have not tried `EM_GETCUEBANNER` yet.

```cs
pub unsafe fn set_placeholder_text<'a>(handle: HWND, placeholder_text: &'a str) {
    //use winapi::um::winuser::EM_SETCUEBANNER;
    use winapi::um::winuser::SendMessageW;

    let text = to_utf16(placeholder_text);
    SendMessageW(handle, 0x1501, 0, text.as_ptr() as LPARAM);
}
```
I can try to implement this properly and make a pull request. 😄

**Comment by gabdube** [comment]
Go for it! If the get don't work you can just leave it out.

**Comment by morshcode** [comment]
The get seems tricky but I'll give it a go. I found this:

> https://microsoft.public.vc.mfc.narkive.com/nNfEeSxu/sigh-more-brain-dead-design-getcuebanner
If you anlyze the code of CWnd::EnlargeBufferGetText<T> in afxwin.h, you can
see that it uses a loop, starting from 256 maximum character count up until
INT_MAX, and it doubles the size of the temporary buffer at each loop
iteration, until the returned string is not truncated, and the maximum limit
of INT_MAX is not surpassed.

Seems like you cannot query the length of the cue banner, that means that you have to allocate for example 256 bytes, fetch the text, inspect it and see if there's a `\0` somewhere, if there is not, increase the buffer size and fetch the cue banner again. I'll see what I can do!

Also it seems like the cue banner should work for the ComboBox as well, I'll see if it works the same way as it does on the TextInput.

> https://docs.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-combobox_setcuebannertext

**Comment by gabdube** [comment]
Right now when the API can't return the length of a string I let the user choose the buffer size. You should do that.

**Comment by morshcode** [comment]
That sounds good, let's leave it up to the user 👍

**Comment by gabdube** [comment]
I finished the branch myself
