### ISSUE TITLE
Size constraint on Window

### ISSUE THREAD

**Issue by morshcode** [gabdube/native-windows-gui#120]
Hey,

It would be really nice to be able to set the minimum/maximum size of a Window.

I believe it can be accomplished by using:
> https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-getminmaxinfo

See this for an example:
> https://stackoverflow.com/a/22261818

What do you think?

Thanks!

**Comment by gabdube** [comment]
It's already possible, see this example: https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/min_max_size_d.rs

Not the prettiest way of doing things, but I have to work with what Windows gives me. If the example is unclear, just ask your question in here.

**Comment by morshcode** [comment]
Awesome, I missed the example. Thanks for the quick reply and your great work with this library! 👍
