### ISSUE TITLE
Unable to set the width of columns in dataview?

### ISSUE THREAD

**Issue by chn-cutelotus** [gabdube/native-windows-gui#124]
And unable to deselect items of treeview, which is an unsolved old issue .

**Comment by gabdube** [comment]
To set the width of a column, use 

```rust
dv.update_column(column_index, nwg::InsertListViewColumn { width: Some(500), ..Default::default() }); 
```

The ignored parameters of `InsertListViewColumn ` wont be updated

**Comment by chn-cutelotus** [comment]
That's amazing. Thanks a lot.
