### ISSUE TITLE
Can't convert ImageData to Bitmap

### ISSUE THREAD

**Issue by Kolsky** [gabdube/native-windows-gui#127]
Steps to reproduce:
Clone the repo.
cargo run --example image_decoder_d --features "image-decoder file-dialog"
Open any supported image except bmp.
Edit image_decoder_d.rs example by replacing this:
```rust
fn read_file(&self) {
        let image = match self.decoder.from_filename(&self.file_name.text()) {
```
to this:
```rust
fn read_file(&self) {
        use std::fs::File;
        use std::io::prelude::*;
        let mut file = File::open(&self.file_name.text()).unwrap();
        let mut buf = Vec::new();
        file.read_to_end(&mut buf).unwrap();

        let image = match self.decoder.from_stream(&buf) {
```
Compile again and try to open the same image as before.

What was expected: both times image will be shown.

Outcome: printed additional line "Could not convert image to bitmap!" in a second case. Other printed info about ImageSource and ImageData remained intact.

**Comment by Kolsky** [comment]
I narrowed down the source of a bug to the IWICStream method called InitializeFromMemory (./native-windows-gui/src/win32/image_decoder.rs, line 67). According to the [official documentation](https://docs.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicstream-initializefrommemory), 
>This method should be avoided whenever possible. The caller is responsible for ensuring the memory block is valid for the lifetime of the stream when using InitializeFromMemory. A workaround for this behavior is to create an IStream and use 
InitializeFromIStream to create the IWICStream.

However, Vec is dropped before decoder could have a chance to convert an image, so we get a dangling pointer or something. 
I've modified code so create_decoder_from_stream and dependent functions took &mut Vec as a parameter and it worked flawlessly. It's up to a better designer to make changes in api for better compliance with rust idioms, but I might be able to fix it myself at some point.

**Comment by gabdube** [comment]
Merged, thanks for your contribution!

**Comment by gabdube** [comment]
Reopen because we might have a simpler solution after all. See lastest comment on #128

**Comment by Kolsky** [comment]
#129

**Comment by gabdube** [comment]
nice
