### ISSUE TITLE
examples\basic.rs: border is not full visible

### ISSUE THREAD

**Issue by vmcrash** [gabdube/native-windows-gui#132]
I'm running the basic.rs example on Windows 10 version 2004 with Rust 1.47.0 and in the occurring window the input field lacks the top and button borders initially.
![screenshot](https://user-images.githubusercontent.com/853847/95505464-a9a42b00-09ae-11eb-8478-7e6f1fe42417.png)

**Comment by gabdube** [comment]
The win32 textinput needed a patch in order to be displayed correctly and this bug happens when the font is too large. I'll look into it

**Comment by gabdube** [comment]
Should be ok now
