### ISSUE TITLE
partials & parent frame/window passing

### ISSUE THREAD

**Issue by RustyJoeM** [gabdube/native-windows-gui#134]
Hello,

i started to restructure my growing app into several NwgPartial elements to simplify/separate code a bit.
I'm using derive macros. One potential issue that bit me is the explicit need to set parent for dynamically added elements:

`thread 'main' panicked at 'Failed to create token: ControlCreationError("No parent defined for \"ComboBox\" control")',`

Issue/solution with my code is obvious, as original code (example of dynamically handled elements) has:

```
nwg::ComboBox::builder()
    ...
    .parent(&self.some_frame)
```

With partials however, frame (mount point), is external to the partial (partials_d example)...

Is it possible to get the parent of the partial struct dynamically from the inside of partial?
(i didn't find a explicit method, but worth asking)

Or do i need to pass the frame reference as parameter of NwgPartial method that does the dynamic changes? (my current implementation)

I see similar pattern with "window" required for file dialog's .run() method.
I just pass the window reference into partial handler, but question is whether this is recommended / the only possible  approach.

**Comment by RustyJoeM** [comment]
adding extra wrapper frame (plus layout) inside the partial could be an option too of course, but feels like extra weight

**Comment by gabdube** [comment]
In NWG, a partial should be self contained. So, outside of the setup phase, it shouldn't have access to the parent interface. If you have a partial that adds comboboxes to itself, then a wrapper frame is the beast way to do this.

If your partial needs a reference to the parent window for some action, it should provide a public method that can be called from the base UI. For example:

```rust
#[derive(Default, NwgUi)]
pub struct Main {
  //...
  #[nwg_partial(parent: window)]
  #[nwg_events( (show_dialog, OnButtonClick): [Main::on_dialog] )]
  par: Partial
}

impl Main {
  fn on_dialog(&self) {
    self.par.popup_dialog(&self.window);
  }
  
}

#[derive(Default, NwgPartial)]
pub struct Partial {
  #[nwg_control]
  show_dialog: nwg::Button
}

impl Partial {

  pub fn  popup_dialog(&self, parent: &Window) {
    // ...
  }
 
}

```

**Comment by RustyJoeM** [comment]
Thanks for confirmation, yes, this is exactly the way how i implemented it (public method of Partial).

I had little doubts about "duplicating" the frames in both main to attach partial, and partial itself.
I wondered whether another alternative exits to the explicit passing of parent frames/window via public methods...
Truth is that need for such param passing is not that frequent (at least in my scenario).
