### ISSUE TITLE
can't find any example！

### ISSUE THREAD

**Issue by GentleVincent** [gabdube/native-windows-gui#140]
I can't find any example when I click the link "showcase" from document, as below shows.
![IMG_20201104_214429](https://user-images.githubusercontent.com/49094111/98119650-dda83880-1ee7-11eb-8548-d063c7d71dff.jpg)
![IMG_20201104_214413](https://user-images.githubusercontent.com/49094111/98119671-e436b000-1ee7-11eb-9435-b82ac19acbd3.jpg)

**Comment by gabdube** [comment]
I'll fix the link :) It should link to https://github.com/gabdube/native-windows-gui/tree/master/showcase

For a code example there's  https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/image_decoder_d.rs

**Comment by gabdube** [comment]
Done
