### ISSUE TITLE
STATUS_ENTRYPOINT_NOT_FOUND

### ISSUE THREAD

**Issue by larspensjo** [gabdube/native-windows-gui#142]
I get this error when I try any example. I am using Rust (GNU ABI) 1.46.0 on Windows 10.

```
PS C:\Users\larsp\src\native-windows-gui\native-windows-gui> cargo run --example basic
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `C:\Users\larsp\src\native-windows-gui\target\debug\examples\basic.exe`
error: process didn't exit successfully: `C:\Users\larsp\src\native-windows-gui\target\debug\examples\basic.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
```

My guess is that some dll fails to load, but I don't know which one. This happens very early, I can't set any breakpoint and catch it.

**Comment by gabdube** [comment]
Yeah you can't use the GNU build with native-windows-gui. It's missing something.

**Comment by larspensjo** [comment]
Thanks, confirmed! I switched to Rust (Windows Studio ABI), and it now works.

I take it that the plan is not to make this library work for the GNU build? If so, please update documentation or readme.

**Comment by larspensjo** [comment]
Thanks, confirmed! I switched to Rust (Windows Studio ABI), and it now works.

Found the comment in the readme now, please excuse me for not reading it through!
