### ISSUE TITLE
Please support gnu

### ISSUE THREAD

**Issue by gilescope** [gabdube/native-windows-gui#143]
I figured we could do with a placeholder issue for people to like if they'd appreciate gnu toolchain support.

btw could you do a compile_error!("We don't support gnu toolchain for now") with a cfg_if target = gnu? That would get people less confused.

**Comment by gabdube** [comment]
I haven't committed in a while so I'll try to fix this now. 99% sure I just need to replace `GetWindowSubclass` anyway

**Comment by gabdube** [comment]
Fixed and released under `1.0.7`
