### ISSUE TITLE
Any way to get the value of a NumberSelect?

### ISSUE THREAD

**Issue by johnshew** [gabdube/native-windows-gui#144]
I am probably missing something, but there doesn't appear to be any NumberSelect function to get/set the value (or the min, max, increment).

Also, tried accessing directly but NumberSelect::data is private.

Couldn't find an example.  Suggestions on how to do this?

**Comment by gabdube** [comment]
I forgot the setter and the getter. It is fixed in the latest commit now. Use `number_select.data()` and  `number_select.set_data()`

**Comment by johnshew** [comment]
Thanks Gabe!
