### ISSUE TITLE
ex_flags

### ISSUE THREAD

**Issue by cg31** [gabdube/native-windows-gui#147]
The windows extra flags are very useful, some of the flags (e.g WS_EX_CLIENTEDGE, or WS_EX_STATICEDGE) will make controls look quite different. It will make app look "normal" like the app developed in C/C++.

But it seems there is no way to set ex_flags for controls from user side now. So, is there any plan for support it?

One example is to change list_box.rs and the look is different:
```
  .flags(flags)
+ .ex_flags(WS_EX_CLIENTEDGE)
  .size(self.size)                                                                                                                                                                  
```

**Comment by gabdube** [comment]
I can add some builder fields. I just didn't know they could be useful to use from an user perspective so I never bothered to write the boilerplate.

**Comment by cg31** [comment]
Exposing it through builder will be fine. Users can pick what they need from winapi-rs:

```
use winapi::um::winuser::{WS_EX_WINDOWEDGE, others}
...
wg::ListBox::builder()
	.collection(vec!["People", "Animals", "Food"])
	.focus(true)
	.parent(&data.window)
+   .ex_flags(WS_EX_CLIENTEDGE)
    .build(&mut data.list)?;
```

**Comment by gabdube** [comment]
Added ex_flag to all controls that can use them in my latest commit, it works just like in your example.
