### ISSUE TITLE
Dynamic Layout like MFC

### ISSUE THREAD

**Issue by cg31** [gabdube/native-windows-gui#149]
It seems the two layout managers will scale controls like button and text input, it is behavior not like common applications.

So I am working on a new Dynamic Layout like MFC:
https://docs.microsoft.com/en-us/cpp/mfc/dynamic-layout?view=msvc-160
https://mariusbancila.ro/blog/2015/07/27/dynamic-dialog-layout-for-mfc-in-visual-c-2015/

A first experimence change set has been committed:
https://github.com/cg31/native-windows-gui/commit/4cd2b019f3c2e7587cb156add879a65793139a5e

there is a demo to show try it:
cargo run --example dyn_layout

**Comment by gabdube** [comment]
Just tried it and it looks great!

**Comment by cg31** [comment]
I just did some improvement. Sure there is more to do.

How about I create a pull request and you merge it?

**Comment by gabdube** [comment]
You can create a PR, I'll merge it after doing the QA. Don't forget to feature-gate it, you can use the feature name `dynamic_layout` .

Also, we will need to add support for `nwg_layout_item` too, but I can handle it. The derive code for the macro is pretty messy.

**Comment by gabdube** [comment]
Also, you need to add a documentation section in native-windows-docs/layouts.html . From the look of it, you can almost copy the gridlayout doc. Use pygments ( https://pygments.org/demo/ ) for the syntax highlighter.
