### ISSUE TITLE
uFlags to TrackPopupMenu 

### ISSUE THREAD

**Issue by cg31** [gabdube/native-windows-gui#153]
The uFlags to TrackPopupMenu is quite useful:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-trackpopupmenu

for example, TPM_BOTTOMALIGN will pop a menu upward.

but in NWG, it is hard-coded as zero:
https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/src/controls/menu.rs#L105

is it possible to add a third argument to Menu::pop(..)?

**Comment by gabdube** [comment]
In order to keep compatibility with older versions, we can add another method `Menu::popup_with_flags(x, y, flags)` where flags use the bitflags macro to wrap the winapi values

**Comment by gabdube** [comment]
Implemented. Also there's a new version of NWG out `1.0.8` that includes all the recent changes.

**Comment by cg31** [comment]
Great, it looks nice now:

https://github.com/cg31/shadowsocks-windows-gui-rust/blob/main/src/dialog.rs#L166

**Comment by gabdube** [comment]
ooohhh interesting.  So are you liking NWG so far? I see you had to implement your own dispatch_events and that you have single line helpers for the bitmap resource.

**Comment by cg31** [comment]
Yeah, I like it, very much. I used to program GUI in WTL, NWG reminds me of it.

I need to detect Escape key to hide the app, implemeting my own dispatch_events to call GetAsyncKeyState seems the natural way to do it. Now I also realize--or recall the experience in WTL--that NWG (or any other GUI library) doesn't need to provide everything, I can use winapi to achieve special features, 

The single-line helpers are in my utils.rs. they are commonly used in GUI, it will be helpful to users if NWG has something like them.
