### ISSUE TITLE
Multiline labels require manual sizing 

### ISSUE THREAD

**Issue by NiceneNerd** [gabdube/native-windows-gui#157]
It seems that it is impossible to show multiline Label widgets unless you size them manually. Example
```rust
pub struct Workshop {
    #[nwg_control(size: (800, 450), position: (283, 233), title: "UKing Workshop", flags: "WINDOW|VISIBLE")]
    #[nwg_events( OnWindowClose: [Workshop::close] )]
    window: nwg::Window,

    #[nwg_layout(parent: window, flex_direction: FlexDirection::Column)]
    grid: nwg::FlexboxLayout,

    #[nwg_control(text: "Thank you for downloading UKing Workshop!
    It seems like you must be ready to start modding Breath of the Wild.")]
    #[nwg_layout_item(layout: grid)]
    welcome: nwg::Label,

    #[nwg_control(text: "Next")]
    #[nwg_layout_item(layout: grid)]
    next_button: nwg::Button,
}
```
This produces the following: 
![image](https://user-images.githubusercontent.com/6720029/104184471-21805800-53d9-11eb-85c8-df8e552c5f75.png)

I've tried several other tricks and variants, but nothing seems to allow the second line to display except manually setting the size, in which case it works:
![image](https://user-images.githubusercontent.com/6720029/104184696-78862d00-53d9-11eb-8494-f80ee5c3f277.png)

**Comment by gabdube** [comment]
Hmmmm, the only way to get the text height in winapi AFAIK is to render the text to call `DrawTextW` and then lookup the resulting bounding rect, but I think this method ignores newlines.  I'll see what I can do.

**Comment by NiceneNerd** [comment]
Also, is there a way to align the text to the top of the label instead of the middle? I looked over the API but couldn't find anything.

**Comment by gabdube** [comment]
There's no built-in way to do that with winapi, but it can be manually implemented. I think I just forgot about it. I'll add this as a todo for this issue. It's going to be called `h_align`

**Comment by gabdube** [comment]
The label `v_align` in in master. Ex:

```
#[nwg_control(text: "Test", v_align: nwg::VTextAlign::Top, h_align: nwg::HTextAlign::Center)]
```

**Comment by gabdube** [comment]
Sorry for the wait! Should be good now.
