### ISSUE TITLE
FileDialog does not support exotic windows paths

### ISSUE THREAD

**Issue by Serranya** [gabdube/native-windows-gui#161]
FileDialog::get_selected_item() returns a rust String. Rust strings need to be valid unicode. UTF-8 to be specific.

nwg tries to create a valid rust string here:
https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/src/win32/base_helper.rs#L35-L43

This funcation will fail with "Decoding error" if the string is not valid UTF-16. Sadly windows paths are not guaranteed to be valid UTF-16. The file Dialog should instead return OsString which can represent those paths.

Example code to create an directory which the FileDialog can not correctly open right now:
```rust
let source = [0x0066, 0x006f, 0xD800, 0x006f];
let os_string = OsString::from_wide(&source[..]);
std::fs::create_dir(os_string);
```

**Comment by gabdube** [comment]
TIL. `get_selected_item` and `get_selected_items` now return OsString
