### ISSUE TITLE
Hidpi not used in OnMinMax methods

### ISSUE THREAD

**Issue by xooler** [gabdube/native-windows-gui#164]
Hi!
I found bug: if i use hidpi app support in manifest and want to control window min (or max, or maximized state) size, passed parameters not convert to logical pixels using hidpi mod.
To fix it add to MinMaxInfo impl methods convertion functions from native-windows-gui/src/win32/high_dpi.rs.
Thank you for this crate.

**Comment by gabdube** [comment]
I just pushed to fix to master.

**Comment by xooler** [comment]
Thank you. I think it solve problem (cant check now), i close issue
