### ISSUE TITLE
Leaked HBRUSH object

### ISSUE THREAD

**Issue by roblabla** [gabdube/native-windows-gui#166]
While going over the code to get familiar with it, I noticed a recurring theme: background color HBRUSH get leaked, never getting freed. See for example Label's background color created [here](https://github.com/gabdube/native-windows-gui/blob/af43f4e6f7c48000e76a2b8e196ce6a6e260d0f9/native-windows-gui/src/controls/label.rs#L219).

I think it might be worth it to create an owned "HBrush" structure with a `Drop` implementation that calls `DeleteObject`, that could live inside the callback object, so it gets freed when the callback gets deallocated?

There's a lot of unsafe manual object management in the code, I wonder if it might benefit from creating a set of wrappers to avoid this kind of pitfall.

**Comment by gabdube** [comment]
I'll fix that. As for the object management, I think it's fine as it is, beyond background brushes the controls don't create much resources.

**Comment by gabdube** [comment]
Better late than never. Background brushes are now freed.
