### ISSUE TITLE
one-time sponsoring option maybe ?

### ISSUE THREAD

**Issue by ffred** [gabdube/native-windows-gui#176]
Hi @gabdube ,

first of all, thanks for your work. I'm learning Rust and discovered nwg recently; it's a great job, thanks !
don't have much time to progress with Rust, but got a few little personal projects to motivate me and I will probably use nwg a little.
was just considering to "sponsor" you, but just for a one-time payment right now and there's only recurrent monthly payment available..
I don't know much of github sponsoring, but if it's easy to add a one-time payment option, maybe you could consider it.

**Comment by gabdube** [comment]
Thank you! I really hope native-window-gui will meet all your GUI needs, and if not fell free to open an issue. I'm always working on improving it.

I looked into it, and yes Github sponsors supports single donation and custom amount too. So I enabled both.

**Comment by ffred** [comment]
ok, thanks. done..
