### ISSUE TITLE
future wysiwyg creator option ?

### ISSUE THREAD

**Issue by ffred** [gabdube/native-windows-gui#177]
Hi @gabdube ,
just saw that there is a "wysiwyg" branch, does that mean that there could be some kind of wysiwyg UI creation possibility sometime ? would be great to be able at least to place the different controls visually when creating a bigger interface. big time saver..

**Comment by gabdube** [comment]
Yes!. The wysiwyg branch has an application that will let you build NWG UIs by drag and dropping controls, but it is far from being usage (it's about 15% done).  At some point I'll go back to it.

**Comment by ffred** [comment]
interesting..  👍
