### ISSUE TITLE
Prevent the cmd window when opening the generated .exe application

### ISSUE THREAD

**Issue by xhh** [gabdube/native-windows-gui#178]
I've just tried the example from the "Getting Started" section of the docs, generating the .exe files with both `cargo build` and `cargo build --release`, but there's a cmd windows poped up first when opening the generated application:

![](https://i.imgur.com/yqzJFu8.png)

Is there a way to prevent that cmd window and open the application directly?

**Comment by gabdube** [comment]
Yes, this works as intended. Just in case you didn't already know, you have to include `#![windows_subsystem = "windows"]`

**Comment by xhh** [comment]
Thanks! I'm new to Rust and have only searched the issues in this repo, should search on the internet as well.
