### ISSUE TITLE
How to programatically close the GUI application?

### ISSUE THREAD

**Issue by popey456963** [gabdube/native-windows-gui#180]
Is there a way to close the UI, without the user clicking the 'X' button in the top-right?  We've tried `nwg::stop_thread_dispatch()` but the UI still seems to run.

**Comment by gabdube** [comment]
The window control has a `close` method. This will trigger the OnWindowClose event and close the window as if the user clicked on the x button. You still need to call `stop_thread_dispatch` somewhere to exit windows event loop
