### ISSUE TITLE
Can edit a treeview item's text when double click the item?

### ISSUE THREAD

**Issue by wuyb66** [gabdube/native-windows-gui#182]
I want to edit a treeview item's text when double click the item. Can this be done and how should it be done? Thanks!

**Comment by wuyb66** [comment]
According to Windows Controls API description, I added the following two functions to treeview.rs. But both are not working. What's the problem?

    pub fn edit_label_a(&self, item: &TreeItem){
        use winapi::um::commctrl::TVM_EDITLABELA;
        let handle = check_hwnd(&self.handle, NOT_BOUND, BAD_HANDLE);

        wh::send_message(handle,  TVM_EDITLABELA, 0, item.handle as HTREEITEM as LPARAM);
    }

    pub fn edit_label_w(&self, item: &TreeItem){
        use winapi::um::commctrl::TVM_EDITLABELW;
        let handle = check_hwnd(&self.handle, NOT_BOUND, BAD_HANDLE);

        wh::send_message(handle,  TVM_EDITLABELW, 0, item.handle as HTREEITEM as LPARAM); 
    }

**Comment by gabdube** [comment]
Not sure `TVM_EDITLABELA` works correctly, I think that's why it wasn't implemented. You will be better off by catching the `OnTreeViewDoubleClick` event an then create a simple text dialog.

**Comment by wuyb66** [comment]
Need to set TVS_EDITLABELS to enable label edit from https://docs.microsoft.com/en-us/windows/win32/controls/tree-view-control-window-styles. Add TVS_EDITLABELS to function flags, send message TVM_EDITLABELA  can enter into edit state. But press key Enter can't exit the edit state and the modify content can't be kept. Can't capture the key press with event OnKeyPress.
How to capture the event when press key Enter/Esc? Thanks!
    pub fn flags(&self) -> u32 {
        use winapi::um::commctrl::{TVS_HASBUTTONS, TVS_LINESATROOT, TVS_HASLINES, **_TVS_EDITLABELS_**};

        WS_VISIBLE | TVS_HASBUTTONS | TVS_LINESATROOT | TVS_HASLINES | WS_TABSTOP | TVS_SHOWSELALWAYS | TVS_EDITLABELS
    }

**Comment by gabdube** [comment]
So I've looked into it and it seems editing labels must be done manually: https://docs.microsoft.com/en-us/windows/win32/controls/tree-view-controls#tree-view-label-editing

You will need to bind a raw event handler see `https://gabdube.github.io/native-windows-gui/native-windows-docs/low_events.html` and process the messages yourself. You have to catch the TVN_ENDLABELEDIT and set the text yourself.

**Comment by wuyb66** [comment]
TVN_BEGINLABELEDIT and TVN_ENDLABELEDIT can be added into function tree_commands.TVN_BEGINLABELEDIT can be received when enter into editing state and TVN_ENDLABELEDIT can be triggered when click other treeitem. 
For my understanding, when begin editing the right of control should be moved to edit control from treeview control. Any key press event will be received by the edit control instead of treeview control. From WINAPI description,  TVM_GETEDITCONTROL message can be sent to get the handle of edit control. If the press key is Enter/Esc, send TVM_ENDEDITLABELNOW to complete/cancel the editing. But I have no idea about how to capture the key press event of the edit control. Do you have any suggestion? Thanks!

**Comment by wuyb66** [comment]
The functionality can be implemented with the reference to https://stackoverflow.com/questions/46193180/how-to-cancel-item-label-editing-in-tree-view-control-upon-esc-keydown-in-winapi. Need to save the handle when TVN_BEGINLABELEDIT received. I can't find a place to store the value and used a static variable for it. It is not very elegant and may be not in line with the existing style. Any other ideas?

**Comment by gabdube** [comment]
I think this is a feature that should be implemented at the  framework level.  That would mean adding a few TreeView events: `OnTreeViewBeginItemEdit`, `OnTreeViewEndItemEdit`. You save the edit handle in the treeview, then you would have a `current_edit` function what return the wrapped handle in `TextInput` .

**Comment by wuyb66** [comment]
Yes, OnTreeViewBeginItemEdit and OnTreeViewEndItemEdit will be added. I double checked the stored handle, it is the treeview's handle and no need to store. Currently, there is one issue left. Two events OnKeyEnter and OnKeyEsc will be added for press key Enter/Esc. The key press event will be back via WM_COMMAND and without class_name and handle. Only base_handle can be gotten when receiving the WM_COMMAND event. So the OnKeyEnter and OnKeyEsc will be capatured by the window instead of treeview. Need to check if it is triggered by the treeview in the application. Do you think it is reasonable?

**Comment by gabdube** [comment]
If the `OnKeyEnter` and `OnKeyEsc ` will be used to save/cancel the content of the treeview, I think you should rename them to `OnTreeViewSaveItemEdit` and `OnTreeViewCancelItemEdit`.   OnKeyEnter and OnKeyEsc looks too generic.

Also to catch the ENTER and ESC keys, I'm not sure why they would need to be captured by the window? But go for it.

**Comment by wuyb66** [comment]
There is no class name and handle included in the WM_COMMAND event when press ket Enter/Esc and only base_handle can be used. So base_handle used in callback and OnKeyEnter/OnKeyEsc will be capatured by the window. Any method to get the treeview's handle for such case?
            match &class_name as &str {
                "Button" => callback(button_commands(message), NO_DATA, handle),
                "Edit" => callback(edit_commands(message), NO_DATA, handle),
                "ComboBox" => callback(combo_commands(message), NO_DATA, handle),
                "Static" => callback(static_commands(child_handle, message), NO_DATA, handle),
                "ListBox" => callback(listbox_commands(message), NO_DATA, handle),
                _ => {
                    match w as i32 {
                        IDOK | IDCANCEL => callback(no_class_name_commands(w), NO_DATA, base_handle),
                        _ => {}
                    }
                }
            }
 OnKeyEnter/OnKeyEsc capatured by the window may have other benefits as well. For example, OnKeyEnter can be used for TextInput control. We may want to do some actions such as search, validation check when press Enter after finished input. However, need to check the event triggered by which control.
