### ISSUE TITLE
`impl From<NumberSelect> for ControlHandle` missing.

### ISSUE THREAD

**Issue by TDecki** [gabdube/native-windows-gui#192]
If the documentation is anything to go by, almost every control that has public access to its `handle` field has a `From<_> for ControlHandle` implementation.

However, `NumberSelect` is an exception. Since it has a public `handle` field, I think that there was supposed to be one,
but was simply forgotten.

**Comment by gabdube** [comment]
Yup, this is an oversight. Just fixed it.
