### ISSUE TITLE
Request: add icon to executable file

### ISSUE THREAD

**Issue by LovaTahina** [gabdube/native-windows-gui#194]
Hi,

Is it possible to set an icon to the binary .exe on windows? Could you add an example for that, please?
Thanks in advanced.
Lova

**Comment by schroeder-** [comment]
You can use [winres](https://github.com/mxre/winres) for this.

**Comment by LovaTahina** [comment]
Thanks

**Comment by gabdube** [comment]
For completeness, there is also [https://docs.rs/embed-resource/1.6.3/embed_resource/](embed_resource). Which I use the the embed_resource example.
