### ISSUE TITLE
Capturing globally registered hotkeys

### ISSUE THREAD

**Issue by giotiskl** [gabdube/native-windows-gui#195]
First off, let me say I am a beginner in Rust and to this library so there might be an easy solution to this.

I've been trying to bind a raw event handler, which will allow me to capture the [WM_HOTKEY](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-hotkey) event globally for whenever a given hotkey I've registered with [RegisterHotKey](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey). I want this hotkey to be captured even if the focused HWND doesn't belong to my process.

This is what my code looks like right now:
```
pub fn register_hotkey() {
  unsafe {
    RegisterHotKey(
      HWND::NULL,
      CUSTOM_HANDLER_ID as i32,
      MOD_CONTROL | MOD_SHIFT,
      'X' as u32,
    );
  };
}
```

And to register the raw event handler:
```
 let raw_handler = bind_raw_event_handler(
        &ui.window.handle,
        CUSTOM_HANDLER_ID ,
        |_hwnd, msg, _w, l| {
          match msg {
            WM_HOTKEY => {
              println!("Hotkey called");
            }
            _ => {
              println!("Some other evt")
            }
          }

          None
        },
      );
```

My problem is that although the raw handler is registered fine (I do get console output for the "Some other evt" line which is capture-all), I cannot get my registered hotkey to trigger.

I took a look at the source code and I saw that in the implementation of `pub fn dispatch_thread_events` there's a check for `IsDialogMessageW` (https://github.com/gabdube/native-windows-gui/blob/d0ab1cdacd83b73572907e5f064a4c3a02458e99/native-windows-gui/src/win32/mod.rs#L49)

Could it be that my event is not fired because of this check?

Thank you in advance for the time taken to look at the question :)

**Comment by gabdube** [comment]
In your set hot key function, I think you should pass the window handle. Something like

```
pub fn register_hotkey(window: &Window) {
  unsafe {
    RegisterHotKey(
      window.handle.hwnd().unwrap(),
      CUSTOM_HANDLER_ID as i32,
      MOD_CONTROL | MOD_SHIFT,
      'X' as u32,
    );
  };
}
```

That's because native-windows-gui doesn't have the ability to catch message that are not assigned to a window instance.

IsDialogMessage is used to support moving the current focus with the TAB key btw.

**Comment by giotiskl** [comment]
Hey thanks for the response, ok I will look into this. As a matter of fact, I tried it earlier but I am using https://github.com/microsoft/windows-rs for my windows bindings and I had some trouble converting successfully the types.

`let hwndmut = ui.window.handle.hwnd().unwrap();` is of type `*mut __HWND` (from the winapi-rs lib that `native-windows-gui` uses internally) and `RegisterHotKey` expects an HWND which is [this struct ](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Foundation/struct.HWND.html)

I guess I'll have to look a bit more into how I can successfully cast to the needed type.

**Comment by gabdube** [comment]
I also use windows-rs in another project. Wish it was there when I started the project. I think this code should world to convert the value:  `HWND(window.handle.hwnd().unwrap() as isize)`

**Comment by giotiskl** [comment]
Thank you so much 👍🏻 This converted the value successfully and passing the HWND instance to `RegisterHotKey` did the trick.

My hotkey now triggers as expected 🎉 

Also thanks for the work on this awesome lib, I'd love to contribute in the future as I get deeper into Rust.

**Comment by gabdube** [comment]
Good! And if you want to add a new feature, you could start with the Hotkey 👍 . Don't feel pressured though
