### ISSUE TITLE
nwg::Label with custom text color

### ISSUE THREAD

**Issue by giotiskl** [gabdube/native-windows-gui#198]
Hello again,

I am sorry if this is an obvious question but I am having a bit of an issue figuring out how to set a custom text color on an `nwg::Label` or `nwg::RichLabel` component.

I could not find a relevant prop in either the NWD or the `builder` API (e.g. there's text_color for RichText but not for labels). I also didn't find anything like this in the examples or the docs.

Furthermore, I tried using [SetTextColor](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-settextcolor) getting an HDC from the Label component also couldn't get this to work.

Any hint would be appreciated.

Thanks in advance.

**Comment by gabdube** [comment]
Label does not support colored text. You can set the color of a rich label using the `set_char_format` 

Ex: https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/rich_label_d.rs#L88-L93

**Comment by giotiskl** [comment]
Thank you, that covers my use-case.
