### ISSUE TITLE
Specify Column alignment on List_view

### ISSUE THREAD

**Issue by LovaTahina** [gabdube/native-windows-gui#200]
Hi,
In List_View, I see that ListViewColumnFlags is provided.
But how do I specify alignment for a specific column, let say index 2.

Thanks for help
Lova

**Comment by LovaTahina** [comment]
I tried something like this:
```
grid.insert_column(nwg::InsertListViewColumn{
            index: Some(0),
            fmt: Some(nwg::ListViewColumnFlags::RIGHT),
            width: Some(20),
            text: Some("test".into())
        });
```
But I have a compilation error: 
       fmt: Some(nwg::ListViewColumnFlags::RIGHT),
    |                            ^^^^^^^^^^^^^^^^^^^ could not find `ListViewColumnFlags` in `nwg`

**Comment by gabdube** [comment]
Looks like `ListViewColumnFlags`  is not being exported correctly, fixing this now. Sorry I overlooked your issue.

**Comment by gabdube** [comment]
Ok, it's in. Also, btw, the column at index 0 must have a LEFT aligment, that a Windows limitation.

**Comment by LovaTahina** [comment]
Thank you for your fixes, 
But it seems that native-windows-gui version is still 1.0.12. I suppose you need to increment it to allow us to get last commits.
