### ISSUE TITLE
Flexbox sublayout with nwd?

### ISSUE THREAD

**Issue by giotiskl** [gabdube/native-windows-gui#202]
Hello, I am trying to follow the flexbox sublayout example https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/flexbox_sub_layout.rs and I have a couple of questions.

1. I noticed there's no `flexbox_sub_layout.d.rs` version, are flexbox sublayouts not supported with NWD atm?

2. When I tried to follow the example the more imperative example linked in the file above I get a ```no method named `build_partial` found for struct `FlexboxLayoutBuilder` in the current scope``` when I try to build the sublayout and similarly I get the same error for the `child_layout` method of the main layout (no method found etc).

Thanks in advance for the time taken.

**Comment by gabdube** [comment]
That feature was recently added and it's not yet released. You can point the dependency of the `master` branch to try it. Also, yeah, it's not supported in the derive macro at all for now.

**Comment by giotiskl** [comment]
is there any other way to combine column and rows in laying out elements with the latest release?

**Comment by gabdube** [comment]
You have to use a buffer frame. So BaseFrame -> Horz Layout -> Frame -> VerticalLayout -> Items .

**Comment by giotiskl** [comment]
ok thanks for the tip that'll probably cover my use case for now
