### ISSUE TITLE
the nwg::TextInputFlags is not have the  password input

### ISSUE THREAD

**Issue by shuqiangzhou** [gabdube/native-windows-gui#203]
I want get a hide password input:
```rust
nwg::TextInput::builder()
            .parent(&app)
            .placeholder_text(Some("please input your password"))
 //winapi:ES_PASSWORD
            .flags(0x0020)
            .build(&mut login.password)?;
```
it's should be a password input in html:
![image](https://user-images.githubusercontent.com/26402118/128284229-ce2eebd6-f5a0-42fa-924c-14a48854aeb9.png)

But it can't?

**Comment by gabdube** [comment]
Check out the `password` field in "TextInputBuilder": https://docs.rs/native-windows-gui/1.0.12/native_windows_gui/struct.TextInputBuilder.html#method.password

```rust
nwg::TextInput::builder()
            .parent(&app)
            .placeholder_text(Some("please input your password"))
            .password(Some('•'))
            .flags(0x0020)
            .build(&mut login.password)?;
```

**Comment by shuqiangzhou** [comment]
ok ,thinks very much.
