### ISSUE TITLE
Grid layout do not give the way to create control with fixed size into resizable window

### ISSUE THREAD

**Issue by T4r4sB** [gabdube/native-windows-gui#204]
Sorry if it is wrong, I watch this crate only one day.  But in all examples I see only relative sizes of controls. I tried to play with basic example, but I achieved only relative sizes of controls.  
Very often we need to have a 20px width buttons bar on top, which do not change size when I resize window.

**Comment by gabdube** [comment]
That's not supported by the GridLayout. To achieve something like that you can use  the flexbox layout https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/flexbox_d.rs or dyn layout https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/dyn_layout_d.rs

**Comment by T4r4sB** [comment]
Thank you!
