### ISSUE TITLE
Is there a control for a terminal emulator?

### ISSUE THREAD

**Issue by yancheng199287** [gabdube/native-windows-gui#209]
Plan to develop an ssh gui client. Is there a control for a terminal emulator? Or how do I integrate other terminal emulators into the window? For details about technical implementation or reference cases, thank you.

**Comment by gabdube** [comment]
Sorry, there's none. The closest thing is the rich text box control with a monospace font. Otherwise you can also code your own and render it inside the application using the ExternCanvas control. Easier said than done though.
