### ISSUE TITLE
`OnImageFrameClick` event does not work

### ISSUE THREAD

**Issue by gyk** [gabdube/native-windows-gui#221]
Reproduction code (adapted from the [basic_d](https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/basic_d.rs) example):

```rs
#[derive(Default, NwgUi)]
pub struct BasicApp {
    // ...

    #[nwg_resource(source_file: Some("./test_rc/cog.ico"))]
    icon: nwg::Icon,

    #[nwg_control(icon: Some(&data.icon), size: (280, 70), position: (10, 50))]
    #[nwg_events(OnImageFrameClick: [BasicApp::say_hello])]
    img: nwg::ImageFrame,
}
```

The image is displayed correctly, but the control doesn't respond to the click event.

**Comment by gabdube** [comment]
Thanks for the report, there was an issue with handling image frame that used icons. I just fixed it, it will be in the next release
