### ISSUE TITLE
migrate to windows-rs crate?

### ISSUE THREAD

**Issue by TomzBench** [gabdube/native-windows-gui#223]
This wonderful project is a wrapper around the winapi, or more specifically, the winapi crate.  But the winapi crate seems to only have a single maintainer, doesn't have much updates anymore. Where as microsoft has recently announced official support for their Win32 api with the windows-rs crate.

Do you think it would be of interest to migrate to this windows-rs crate?

**Comment by gabdube** [comment]
Yeah, windows-rs is a better crate and I use it in all my new pet projects, but porting nwg would be mean rewriting 90% of the crate, and I just don't have the heart for that.

**Comment by TomzBench** [comment]
understood! thanks for response
