### ISSUE TITLE
Escape key on text_box closes window

### ISSUE THREAD

**Issue by jmagine** [gabdube/native-windows-gui#233]
For me, inputting the Esc key char on Windows into the text_box control causes a window close event. This isn't the case when Esc is pressed while other controls are in focus, including the base window. Did I possibly structure something incorrectly or is this intentional? Is there some way I can handle this event differently from other window close events (like pressing the x button to close the window)? Thanks.

**Comment by gabdube** [comment]
You did everything right, this is just yet another weird winapi behavior that went under my radar. I'll push a quickfix soon enough for that.
