### ISSUE TITLE
End of Text

### ISSUE THREAD

**Issue by valarauca** [gabdube/native-windows-gui#24]
Is there an event to show when text input ended?

I assumed `SetTextLimit` would do this:

When a `TextInput` is given the `SetTextLimit` it will limit the number of input characters to that value but a `MaxValue` event is never triggered. The `TextInput` just stops accepting input. 

My main issue is I can call `GetText` on every `ValueChanged`, but there is no way I can tell the text is ending without another thread buffering text/comparing timing (also how do I then trigger an even back in my main loop lol). Or having a user click something (breaking flow).

**Comment by gabdube** [comment]
I'm not sure of what you mean by "text input ended". If you want to know when the user is finished with the control, then the `Focus` event is what your are looking for. It will be called when the user select another control.

`When a TextInput is given the SetTextLimit it will limit the number of input characters to that value but a MaxValue event is never triggered. `

That is a bug. If i'm capable to reproduce it, i'll release a patch.


`also how do I then trigger an even back in my main loop `
Multithreading communication is not supported in the alpha (and probably won't be in the beta either). FYI, I've implemented the timer object in the beta for checking stuff asynchronously.

Also just letting that the beta release will have a lot of breaking changes so you might not want to invest too much time on the alpha.

**Comment by gabdube** [comment]
this issue is related to v1 which is not longer developed.
