### ISSUE TITLE
[Feature Request] Control or component to render HTML

### ISSUE THREAD

**Issue by pynem** [gabdube/native-windows-gui#247]
(Similar issue: https://github.com/gabdube/native-windows-gui/issues/227)

I am investigating using NWG as the GUI framework for a Windows application that will use Office 365 single-sign-on to authenticate users. To do this, it would be preferable to display/render the authentication pages/process within the application, rather than passing control to a third-party web browser.

Is this something that can be achieved with NWG?

**Comment by gabdube** [comment]
Rendering HTML is out of scope for this project. Sorry.
