### ISSUE TITLE
Is there any nwg equivalent for AdjustWindowRectEx?

### ISSUE THREAD

**Issue by marethyu** [gabdube/native-windows-gui#255]
I need to calculate the required size for window when menubar is added. C/C++ Win32 API provides this useful function called [AdjustWindowRectEx](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-adjustwindowrectex). Does nwg have this such function? I can't find anything relevant in docs.

**Comment by gabdube** [comment]
NWG doesn't wrap this function, but you can call it yourself by adding winapi to your project.

```toml
# Cargo.toml
winapi =  {version = "0.3", features = ["winuser"]}
```

```rust
use winapi::um::winuser::{AdjustWindowRectEx, RECT, WS_CAPTION};

fn adjust_window_rect() -> RECT {
  unsafe {
    let mut out: RECT = ::std::mem::zeroed();
    AdjustWindowRectEx(&mut out, WS_CAPTION, 1, 0);
    out
  }
}
```

**Comment by marethyu** [comment]
Thanks in order to make your code work, I had to change the imports to
```
use winapi::um::winuser::AdjustWindowRectEx;
use winapi::shared::windef::RECT;
```
because RECT is private.
