### ISSUE TITLE
support icon?

### ISSUE THREAD

**Issue by bitbegin** [gabdube/native-windows-gui#30]

**Comment by gabdube** [comment]
If you are referring the a [static image control](https://msdn.microsoft.com/en-us/library/windows/desktop/bb760767(v=vs.85).aspx#image_static_control) then yes, it will be supported. I might implement it as soon as I'm finish with the datepicker control.

**Comment by gabdube** [comment]
Good news! as of 37dfaf0425a66f455d63f6ff5bc28c81b22ea954 icon resources can be loaded and displayed in a new control: the **ImageFrame** or used a icon for a window.

You can pull the `dev` branch and check the showcase example to test it.

OEM images or images located in packed .res file support will be added later. Feel free to close this issue if the added features fits your need.
