### ISSUE TITLE
support listview?

### ISSUE THREAD

**Issue by bitbegin** [gabdube/native-windows-gui#31]

**Comment by gabdube** [comment]
Listview and treeview are the biggest and most complex controls. I plan to support them, but it will take some time.

**Comment by gabdube** [comment]
The listview is a very complex control. And because of this, I think it should be split into two distinct controls:

- `ListView` control for the simple style ( Icon View, Small Icon View, List view)  
- `DetailedListView` control for the detailed style ( Report View, Tile View)  

The first one will be very similar to the existing `ListBox` control. And should be implemented to behave like it. IE: items are value that the user push onto the control

The second one should behave like the tree-view. This means that each item will be another custom control (likely named `ListViewItem`).  Furthermore, the detailed list view should take a `header` argument at the control creation to determinate how many elements the `ListViewItem` will have.

As for the flickering issue, I don't have a solution yet. 

This is a draft, and it is subject to change  during the development.


See: https://msdn.microsoft.com/en-us/library/windows/desktop/bb774735(v=vs.85).aspx

**Comment by zoumi** [comment]
@gabdube 
I have uploaded my codes to my fork's dev brench.
Now only the listview header flicker.
I try to filter out all WM_NOTIFY messsages in message_handler.rs:: message_window_proc()
but I get a strange error:
The error dialog tells me: There is a fatal error,:A  system error was raised: The system could not initialize the Ui. ID 0 - the operation is successfull.

**Comment by zoumi** [comment]
@gabdube 
Maybe, I found the way solve the blink problem!
These codes are porting from https://github.com/JesperAxelsson/rust-virtual-listview/blob/master/src/main.rs

`
//extern crate kernel32;
//extern crate user32;
extern crate winapi;
extern crate libc;
//extern crate comctl32;
//extern crate ole32;

use std::os::windows::ffi::OsStrExt;
use std::ffi::OsStr;

use std::hash::Hash;
use std::any::TypeId;
use std::mem::{transmute, zeroed, size_of};
use std::thread::sleep;
use std::time::Duration;

use winapi::*;
/*
use winapi::windef::*;
use winapi::minwindef::*;
use winapi::winnt::*;
//use winapi::shared::minwindef::*;
use winapi::um::comctl32::*;
use winapi::um::*;
use winapi::um::ole32::*;

*/
use winapi::um::winuser::*;
use winapi::um::winbase::*;
use winapi::um::commctrl::*;
use winapi::shared::windef::*;
use winapi::shared::minwindef::*;
use winapi::shared::basetsd::*;
use winapi::um::sysinfoapi::*;
use winapi::um::objbase::*;
use winapi::um::winnt::*;
use winapi::um::commctrl::*;
use winapi::um::libloaderapi::*;
//use ole32::*;
//use commctrl::*;
//use comctl32::SetWindowSubclass;

#[macro_use]
extern crate lazy_static;

use std::sync::RwLock;
//use std::ffi::OsStr;
use std::iter::once;
//use std::os::windows::ffi::OsStrExt;
use std::mem;
use std::collections::HashMap;

struct Row {
    item: String, 
    sub_item: String,
}

fn get_all_data() -> Vec<Row> {

    let mut vec = Vec::with_capacity(100);

    for i in 0..100 {
        vec.push(Row {
            item: format!("Item: {:?}", i),
            sub_item: format!("SubItem {:?}", i),
        });
    }

    vec
}


fn to_wstring(str: &str) -> Vec<u16> {
    let mut wide: Vec<u16> = OsStr::new(str).encode_wide().chain(once(0)).collect();
    wide
}

// ************** Constant HWNDS **************
lazy_static! {
    static ref ALL_DATA: RwLock<Vec<Row>> = RwLock::new(Vec::new());
    static ref STRING_CACHE: RwLock<HashMap<String, Vec<u16>>> = RwLock::new(HashMap::new());
}

static mut LIST_HWND: HWND = 0 as HWND;

const IDC_MAIN_LISTVIEW: HMENU = 101 as HMENU;

const MAX_TEXT_LEN: u64 = 250;

// ************ End Constant HWNDS ************

pub unsafe extern "system" fn window_proc(hwnd: HWND, msg: UINT, w_param: WPARAM, l_param: LPARAM) -> LRESULT
{
    match msg {
        WM_CREATE => {
            let mut icc = mem::zeroed::<INITCOMMONCONTROLSEX>();
            icc.dwSize = mem::size_of::<INITCOMMONCONTROLSEX>() as DWORD;
            icc.dwICC = ICC_LISTVIEW_CLASSES;
            
            if InitCommonControlsEx(&icc) == 0 {
                println!("Failed to init component");
            }
            
            test_setup_list(hwnd);

            println!("Running WM_CREATE");
            0
        },

        WM_NOTIFY => {
         
            match (*(l_param as LPNMHDR) as NMHDR).code {
                LVN_GETDISPINFOW => {
           
                    let ix: usize = (*(l_param as *const NMLVDISPINFOW)).item.iItem as usize;
                    let mask = (*(l_param as *const NMLVDISPINFOW)).item.mask;

                    if (*(l_param as *const NMLVDISPINFOW)).item.iItem < 0 {
                        println!("Request Item with negative index:{:?}", (*(l_param as *const NMLVDISPINFOW)).item.iItem);
                        return 0;
                    }
                   
                    if (mask & LVIF_TEXT) == LVIF_TEXT {
                        let len = ALL_DATA.read().unwrap().len();
                        if ix >= len -1 {
                            println!("ix bigger then index! ix: {:?} len: {:?}", ix, len );
                            return 0;

                        }
                        let ref item = ALL_DATA.read().unwrap()[ix];

                        let f = |key| {
                            let ref vec = STRING_CACHE.read().unwrap()[(key)];
                            let ptr = STRING_CACHE.read().unwrap()[(key)].as_ptr();
                            (ptr, vec.len())
                        };

   
                        let (ptr, _) = match (*(l_param as *const NMLVDISPINFOW)).item.iSubItem {
                            0 => f(&item.item),
                            1 => f(&item.sub_item),
                            n => {
                                println!("Found subitem: {:?}", n);
                                return 0;
                            }
                        };

                        (*(l_param as *mut NMLVDISPINFOW)).item.pszText = ptr as LPWSTR; 
                                        
                    }

                    0
                    
                },
                LVN_ODCACHEHINT=> {
                    DefWindowProcW(hwnd, msg, w_param, l_param)
                },
                LVN_ODFINDITEMW => {
                    // let pnfi = l_param as LPNMLVFINDITEMW;
                    println!("Got find item event!");
                    DefWindowProcW(hwnd, msg, w_param, l_param)

                },
                _ => {
                    DefWindowProcW(hwnd, msg, w_param, l_param)
                }
            }

        },
        WM_SIZE => {
            on_size(hwnd, LOWORD(l_param as u32) as i32, HIWORD(l_param as u32) as i32, w_param as u32);
            0
        },
        WM_CLOSE => {
            println!("Got close message");
            DestroyWindow(hwnd) as isize
        }
        WM_DESTROY => {
            println!("Got quit message");
            PostQuitMessage(0);
            0
        },
        4173 => {println!("Got Insert Item"); DefWindowProcW(hwnd, msg, w_param, l_param)}
        4193 => {println!("Got Insert Column"); DefWindowProcW(hwnd, msg, w_param, l_param)}
        _ => DefWindowProcW(hwnd, msg, w_param, l_param)
    }
}

fn on_size(hwnd: HWND, cx: i32, cy: i32, flags: u32) {
    unsafe {
        if cx == 0 {
            println!("OnMove, hwnd: {:?} flags: {:?}", hwnd, flags);
        }

        println!("cx: {:?} cy: {:?}", cx, cy);

        MoveWindow(LIST_HWND, 0, 30, cx, cy-30, 1);
        SendMessageW(LIST_HWND, LVM_ARRANGE, LVA_ALIGNTOP, 0);
    }
}


fn test_setup_list(hwnd: HWND) {

    let list_hwnd = create_list_view(hwnd);

    unsafe {
        LIST_HWND = list_hwnd;
    }

    create_column(list_hwnd, "SubItem", 1);
    create_column(list_hwnd, "Item", 0);


    ALL_DATA.write().unwrap().append(&mut get_all_data());
   

    // Create the cache
    let mut list_write = STRING_CACHE.write().unwrap();

    for e in ALL_DATA.read().unwrap().iter() {
        list_write.insert(e.item.to_string(), to_wstring(&e.item));
        list_write.insert(e.sub_item.to_string(), to_wstring(&e.sub_item));
    }  

    unsafe {
        SendMessageW(list_hwnd, LVM_SETITEMCOUNT, (ALL_DATA.read().unwrap().len()-1), 0);
    }
}


fn create_column(list_hwnd: HWND, text: &str, sub_item: i32) {
    unsafe {
        let text_column = to_wstring(text);

        let col: LPLVCOLUMNW = &mut LV_COLUMNW {
            mask: LVCF_TEXT | LVCF_WIDTH, //LVCF_TEXT | LVCF_IDEALWIDTH | LVCF_WIDTH | LVCF_SUBITEM, // | LVCF_ORDER,
            cx: 200,
            pszText: text_column.as_ptr() as LPWSTR,
            cchTextMax: MAX_TEXT_LEN as i32,
            fmt: 0,
            iSubItem: sub_item,
            cxMin: 200,
            cxIdeal: 200,
            cxDefault: 200,
            iImage: 0,
            iOrder: sub_item,
        };

        if SendMessageW(list_hwnd, LVM_INSERTCOLUMNW, 0, col as LPARAM) != 0 {
            println!("Failed to insert column");
        } 
    }
}


fn create_window(title: &str) -> HWND {
    let class_name = to_wstring("my_class");
    let title = to_wstring(title);

    let icon;
    let cursor;
    unsafe {
        icon = LoadIconW(0 as HINSTANCE, IDI_APPLICATION);
        cursor = LoadCursorW(0 as HINSTANCE,IDI_APPLICATION);
    }

    println!("icon: {:?}", icon);
    println!("cursor: {:?}", cursor);

    let wnd = WNDCLASSW {
        style: 0,
        lpfnWndProc: Some(window_proc), 
        cbClsExtra: 0,
        cbWndExtra: 0,
        hInstance: 0 as HINSTANCE,
        hIcon: icon,
        hCursor: cursor,
        hbrBackground: 16 as HBRUSH,
        lpszMenuName: 0 as LPCWSTR,
        lpszClassName: class_name.as_ptr(),
    };

    let hwnd;

    unsafe {
        // We register our class - 
        if RegisterClassW(&wnd) == 0 {
            println!("Failed to register wnd");
        }

        let h_wnd_desktop = GetDesktopWindow();

        hwnd = CreateWindowExW(
            0, 
            class_name.as_ptr() as *mut _, 
            title.as_ptr() as *mut _,
            WS_OVERLAPPEDWINDOW | WS_VISIBLE, 
            0, 0, 400, 400,
            h_wnd_desktop ,
            0 as HMENU, 0 as HINSTANCE, std::ptr::null_mut());
        
        println!("wnd: {:?}", h_wnd_desktop);

    }

    println!("hwnd: {:?}", hwnd);
        
    hwnd
}


fn create_list_view(hwnd_parent: HWND) -> HWND {
    // This should only run once!
    unsafe {
   
        // Setup actual listview
        
        let wc = to_wstring("SysListView32");
        let h_instance = GetModuleHandleW(std::ptr::null_mut());

        let style =  WS_VISIBLE | WS_CHILD | WS_TABSTOP |
                  LVS_NOSORTHEADER | LVS_OWNERDATA | LVS_AUTOARRANGE |
                  LVS_SINGLESEL | LVS_REPORT;
        let hwnd = CreateWindowExW(
            0, 
            wc.as_ptr() as *mut _,
            to_wstring("").as_ptr() as *mut _, 
            style, 
            0, 0, 0, 0,
            hwnd_parent, 
            IDC_MAIN_LISTVIEW , 
            h_instance, 
            std::ptr::null_mut());

        hwnd

    }
}



fn main() {
    let title = "my_window";
    let hwnd = create_window(title);

    unsafe {
        ShowWindow(hwnd, SW_NORMAL);
        UpdateWindow(hwnd);
    }

    let mut msg = MSG {
        hwnd : 0 as HWND,
        message : 0 as UINT,
        wParam : 0 as WPARAM,
        lParam : 0 as LPARAM,
        time : 0 as DWORD,
        pt : POINT { x: 0, y: 0, },
    };

    println!("Starting msg loop");

    loop {
        let pm;
        unsafe {
            pm = GetMessageW(&mut msg, 0 as HWND, 0, 0);
        }

        if pm <= 0 {
            println!("GetMessageW error: {:?}", pm);
            break;
        }

        unsafe {
            TranslateMessage(&mut msg);
            DispatchMessageW(&mut msg);
        }
    }

    println!("Hello, world!");
}

`

**Comment by gabdube** [comment]
Took me 3 years, but it's finally done. See `ListView` in the 1.0prerelease branch.

**Comment by elibenporat** [comment]
ListView is working great and the example was very helpful. Your documentation is fabulous.

There are a couple of Extended List-View styles that I want to add, specifically the LVS_EX_HEADERDRAGDROP and LVS_EX_HEADERINALLVIEWS.

I'd be happy to submit a PR if that is preferable (will need a bit of time to learn the codebase).

**Comment by gabdube** [comment]
Just pushed those flags to master.  Use `HEADER_DRAG_DROP` and `HEADER_IN_ALL_VIEW` in ListViewBuilder::ex_flags

Still need to find a way to fix the header

**Comment by elibenporat** [comment]
Do you mean figuring out why the headers never show up? I had naively thought that the flags above would address that, but it doesn't appear that way.

**Comment by gabdube** [comment]
Right now NO_HEADER is always on because enabling it leaks a lot of memory and it breaks the drawing.

**Comment by elibenporat** [comment]
Right! Just found that note in the docs now. I was looking for a header titled "Windows is $hit", so missed the simple header "Windows". :) 

Small chance that I'll be able to figure it out, but I'll play around with the repo and maybe I'll get lucky.

**Comment by gabdube** [comment]
Oops. Forgot to clean that.

**Comment by elibenporat** [comment]
Cool. It goes without saying, but please don't feel any time pressure to fix this (or even to fix it at all!). I've got lots more exploring to do here anyway and this is a fantastic resource as is.
