### ISSUE TITLE
 Module 'events' is private

### ISSUE THREAD

**Issue by dex-r** [gabdube/native-windows-gui#38]
Hi, I'm getting the following error when trying to run the [Hello World example given in the docs](https://gabdube.github.io/native-windows-gui/book/getting_started.html):

```
error: module 'events' is private
 --> src\main.rs:8:5
  |
8 | use nwg::events as nwge;
  |     ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
error: Could not compile `filetag`.

Caused by:
  process didn't exit successfully: `rustc --crate-name filetag src\main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=ce45a017d507ce61 -C extra-filename=-ce45a017d507ce61 --out-dir C:\msys64\home\Declan\Code\rust\filetag\target\debug\deps -L dependency=C:\msys64\home\Declan\Code\rust\filetag\target\debug\deps --extern native_windows_gui=C:\msys64\home\Declan\Code\rust\filetag\target\debug\deps\libnative_windows_gui-a0afd57132c386a5.rlib` (exit code: 101)

```

Am I doing something stupid? All the examples work if i run them through cargo 'cargo run --example ...' but not if i start a new project and copy the code over.
I'm on W7 64bit and this is my rust version:
```
stable-x86_64-pc-windows-msvc (default)
rustc 1.17.0 (56124baa9 2017-04-24)
```

[main.rs.txt](https://github.com/gabdube/native-windows-gui/files/1060884/main.rs.txt)
[Cargo.toml.txt](https://github.com/gabdube/native-windows-gui/files/1060885/Cargo.toml.txt)

**Comment by gabdube** [comment]
The new event style is not currently available on cargo. 

That's my fault. I shouldn't have kept the development branch on master. where the official documentation is built (why didn't I see this coming).

**Comment by dex-r** [comment]
Thanks, now runs beautifully :).
