### ISSUE TITLE
support byte array "image"

### ISSUE THREAD

**Issue by bitbegin** [gabdube/native-windows-gui#44]
I want to use include_bytes!() to put image file into source code, so need "image" have an interface to use this byte array.

**Comment by gabdube** [comment]
Good idea. The bitmap format is dead simple so it shouldn't be an issue. This will most likely be implemented as a new template for the Image resource.

It will also pave the way to load image using other format (such as JPEG and PNG)

Something like this:

```rust
ImageFromBytesT {
   pub source: Vec<u8>,
   // other fields?
}
```

**Comment by gabdube** [comment]
I just merged a PR that implements this feature. Check the showcase example for an example.

```rust
static EMBED_BMP01: &'static [u8; 27702]  = include_bytes!("../img/rust-logo.bmp");

// in nwg_templates
("RustLogoMemory", nwg::MemoryImageT{source: Vec::from( &EMBED_BMP01[..] )} )
```

You can close the issue if it fits your needs.
