### ISSUE TITLE
create the "exe" file with Copyright, Author, and time stamp

### ISSUE THREAD

**Issue by bitbegin** [gabdube/native-windows-gui#45]

**Comment by gabdube** [comment]
This is not something that should be done by NWG. Native-Windows-GUI goal is to create gui elements at runtime . Setting the version info of an executable should be done at compile time (ex: using a build dependency) or after the exe was compiled (using a resource editor).

Hopefully I think someone already created a library that can achieve this. See https://github.com/nabijaczleweli/rust-embed-resource . 

Leave this issue open though, I decided I want to include a section in the docs about this.

**Comment by gabdube** [comment]
The documentation was updated with a section on to use rust-embed-resource with NWG.

Closing this
