### ISSUE TITLE
dynamic combobox

### ISSUE THREAD

**Issue by AndreyMakuha** [gabdube/native-windows-gui#46]
Sorry for stupid quiestion, i want to ask how to create dynamic combobox. For example, i have mutable array and want to show it in combobox via templating. Does it possible? Or could you guess how make it better? Thanks.

**Comment by gabdube** [comment]
It's not a stupid question. 

It is possible. Templates should only execute basic initialization in the UI. If you want to load an array dynamically (from a file, for example), it should be done in either a callback or a function.

See this example (based on master):
https://gist.github.com/gabdube/bb09e542f059206109239067fea51cf4

**Comment by AndreyMakuha** [comment]
Thanks a lot! :) it works perfectly. Actually, i need it for showing com ports. just add one function.
https://gist.github.com/AndreyMakuha/9986c8c7d202db1cd245660cbbffd4f8

**Comment by gabdube** [comment]
I'm glad to hear it! Furthermore, if the output will be only loaded once at the start of your program, it is possible to simplify the program even more:

https://gist.github.com/gabdube/5f0eee11010d4daf2af4a5aac1d5243c

Closing this.
