### ISSUE TITLE
examples wont compile.

### ISSUE THREAD

**Issue by cloudcalvin** [gabdube/native-windows-gui#47]
Hello. 

Sorry if this is in fact my fault but I seem to get this same error for all the examples I try.
( I am using ubuntu 16.04 with rustc 1.16.0-nightly (2782e8f8f 2017-01-12) )

$ cargo build && cargo run --example canvas --verbose
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
       Fresh winapi-build v0.1.1
       Fresh winapi v0.2.8
       Fresh ole32-sys v0.2.0
       Fresh gdi32-sys v0.2.0
       Fresh user32-sys v0.2.0
       Fresh comctl32-sys v0.2.0
       Fresh kernel32-sys v0.2.2
   Compiling native-windows-gui v0.2.0 (file:///home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui)
     Running `rustc --crate-name canvas examples/canvas.rs --crate-type bin --emit=dep-info,link -g -C metadata=f368be4115be0f31 -C extra-filename=-f368be4115be0f31 --out-dir /home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/examples -L dependency=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps --extern gdi32=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libgdi32-87959dd4125f07e0.rlib --extern winapi=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libwinapi-3f4827e2e513c3d9.rlib --extern comctl32=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libcomctl32-3f24f77d74a3ac76.rlib --extern user32=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libuser32-e816280001024a43.rlib --extern kernel32=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libkernel32-7cda898cd53d6f66.rlib --extern ole32=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libole32-e3aeb471ded09a78.rlib --extern native_windows_gui=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libnative_windows_gui-5ec02c6c8cc8d552.rlib`
error: macro undefined: 'nwg_template!'
  --> examples/canvas.rs:27:1
   |
27 | nwg_template!(
   | ^^^^^^^^^^^^

error: macro undefined: 'nwg_get_mut!'
  --> examples/canvas.rs:75:22
   |
75 |     let mut canvas = nwg_get_mut!(app; (Canvas, nwg::Canvas<CanvasId>));
   |                      ^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `native-windows-gui`.

Caused by:
  process didn't exit successfully: `rustc --crate-name canvas examples/canvas.rs --crate-type bin --emit=dep-info,link -g -C metadata=f368be4115be0f31 -C extra-filename=-f368be4115be0f31 --out-dir /home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/examples -L dependency=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps --extern gdi32=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libgdi32-87959dd4125f07e0.rlib --extern winapi=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libwinapi-3f4827e2e513c3d9.rlib --extern comctl32=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libcomctl32-3f24f77d74a3ac76.rlib --extern user32=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libuser32-e816280001024a43.rlib --extern kernel32=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libkernel32-7cda898cd53d6f66.rlib --extern ole32=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libole32-e3aeb471ded09a78.rlib --extern native_windows_gui=/home/userd/Workspace/git-local-repos/rust-projects/native-windows-gui/target/debug/deps/libnative_windows_gui-5ec02c6c8cc8d552.rlib` (exit code: 101)

**Comment by gabdube** [comment]
Make sure that the compiler think you are building on Windows (`#![cfg(windows)]`) or else it will output an empty crate (and the macro will not be found).

Also, I see you are trying to compile the "0.2.0" on linux. This wont work because the 0.2.0 release has a bug that makes building on the gnu toolchain impossible.

This was fixed not so long ago on the dev branch  (see https://github.com/gabdube/native-windows-gui/issues/32 for the original issue ). If you want to test it you will have to point to the lastest revision.

**Comment by gabdube** [comment]
I guess I can close this?
