### ISSUE TITLE
[New Feature]Resource files support.

### ISSUE THREAD

**Issue by zoumi** [gabdube/native-windows-gui#49]
I have found something may help:
https://crates.io/crates/embed-resource
WinAPI: LoadIcon
WinAPI: LoadCursor
WinAPI: LoadString
WinAPI: LoadMenu

**Comment by gabdube** [comment]
Partial support implemented for now. LoadIcon, LoadBitmap, LoadString. LoadIcon and LoadCursor will come soon enough. For some example, see the new `embed_resources` example

**Comment by gabdube** [comment]
It's now fully implemented
