### ISSUE TITLE
I need your help(about the listview)

### ISSUE THREAD

**Issue by zoumi** [gabdube/native-windows-gui#52]
I'm trying to the add listview support. But failed.
Can you test my fork? 
https://github.com/zoumi/native-windows-gui
The problem is:
1,after add the listview to the window , all the control will blink
2,can't add the full string to listview cell.(If i add "what is this" it will show "xhat is this")

Here is the code to test the listview:

```
//#![windows_subsystem = "windows"]
//#![feature(link_args)]
//#[link_args = "-Wl,--subsystem,windows"]
//#[link_args = "/SUBSYSTEM:WINDOWS"]
#[macro_use] extern crate native_windows_gui as nwg;

use nwg::{Event, Ui, simple_message, fatal_message, dispatch_events};
extern crate winapi;
use winapi::{LPCWSTR,HWND};

extern "system"{
pub fn SetWindowTheme(hwnd: HWND,
                      pszSubAppName: LPCWSTR,
                      pszSubIdList: LPCWSTR);
}

/// Custom enums are the preferred way to define ui ids. 
/// It's clearer and more extensible than any other types (such as &'str).
#[derive(Debug, Clone, Hash)]
pub enum AppId {
    // Controls
    MainWindow,
    NameInput, 
    HelloButton,
    Label(u8),   // Ids for static controls that won't be referenced in the Ui logic can be shortened this way.
    MyListView,

    // Events
    SayHello,

    // Resources
    MainFont,
    TextFont
}

use AppId::*; // Shortcut

nwg_template!(
    head: setup_ui<AppId>,
    controls: [
        (MainWindow, nwg_window!( title="Template Example"; size=(280, 305) )),
        (Label(0), nwg_label!(
             parent=MainWindow;
             text="Your Name: ";
             position=(5,15); size=(80, 25);
             font=Some(TextFont) )),

        (NameInput, nwg_textinput!( 
             parent=MainWindow; 
             position=(85,13); size=(185,22); 
             font=Some(TextFont) )),

        (HelloButton, nwg_button!( 
             parent=MainWindow; 
             text="Hello World!"; 
             position=(5, 45); size=(270, 50); 
             font=Some(MainFont) )),

        (MyListView, nwg_list_view!(
                parent=MainWindow;
                text="oh my list view";
                position=(5,100);size=(270,200);
                font=Some(MainFont) ))
    ];

    events: [
        (HelloButton, SayHello, Event::Click, |ui,_,_,_| {

            let my_list_view = nwg_get!(ui; (MyListView,nwg::ListView));
           // unsafe { SetWindowTheme}
            my_list_view.insert_col(0,"FIRST",50);
            my_list_view.insert_col(1,"wsec",50);
            my_list_view.insert_col(2,"wtrd",50);
            my_list_view.add(vec!["1fsafas".to_owned(),"ewheh2".to_owned(),"3sfsaga".to_owned()]);
            my_list_view.insert(1,
                vec!["1o8u53b".to_owned(),"iluou2".to_owned(),"3wvrwr".to_owned()]);
            my_list_view.insert(2,
                vec!["1333".to_owned(),"266666".to_owned(),"00003".to_owned()]);
            println!("list_view hwnd: {:?}",my_list_view);
            //let your_name = nwg_get!(ui; (NameInput, nwg::TextInput));
            //simple_message("Hello", &format!("Hello {}!", your_name.get_text()) );
        }),
        (MyListView, SayHello, Event::Notify, |ui,hwnd,wpara,lpara| {
        
        })
    ];
    resources: [
        (MainFont, nwg_font!(family="Arial"; size=27)),
        (TextFont, nwg_font!(family="Arial"; size=17))
    ];
    values: []
);

fn main() {
    let app: Ui<AppId>;

    match Ui::new() {
        Ok(_app) => { app = _app; },
        Err(e) => { fatal_message("Fatal Error", &format!("{:?}", e) ); }
    }

    if let Err(e) = setup_ui(&app) {
        //fatal_message("Fatal Error", &format!("{:?}", e));
    }


    dispatch_events();
}
```

**Comment by gabdube** [comment]
Hey so I don't have the time to look at the details in your code, but I can see a very important thing that you have missed: your have forked `master`. It should been `dev`.

1. Blinking is an issue on its own. I'm not sure it is a problem related to the control itself. 
2. That's weird. I'll have to take a deeper look.

Before going further, please detail the way you want to implement the control on the issue https://github.com/gabdube/native-windows-gui/issues/31 . I originally imagined an structure similar to the TreeView contro (where children are implemented as control too).

**Comment by zoumi** [comment]
Thank you!
I will read the codes you write for the TreeView first.

I had used spy++ to debug the listview before.
I guess the reason is the listview continually send WM_PAINT, WM_NOTIFY, WM_ERASEBKGND,WM_NCPAINT
to the window. But, I don't know how to stop it.

**Comment by bitbegin** [comment]
Good news!

I had the same issue to build listview, and can't figure it out, so I gave up.

**Comment by gabdube** [comment]
I spent hours debugging in order to fix the general flickering, without success. I think the only way to prevent this would be to  implemented manual refreshing over every controls and make sure that only affected area should be repainted. It would take alot of work and I'm not even sure if this is feasible. 

Anyway, if you find something reference this issue: https://github.com/gabdube/native-windows-gui/issues/42

**Comment by zoumi** [comment]
This all controls in a cpp file may help us. But I can't figure out key difference between it's codes and my codes.
https://github.com/AutoHotkey/AutoHotkey/blob/master/Source/script_gui.cpp

**Comment by zoumi** [comment]
I think I have found the reason:
"LVN_HOTTRACK
NM_CUSTOMDRAW
LVN_ITEMCHANGING
LVN_INSERTITEM
LVN_DELETEITEM
LVN_GETINFOTIPW
LVN_GETINFOTIPA
Return immediately to avoid calling Event() and DefDlgProc()"

But it was hard to handle these events by listview itself in NWG. 
Because controls in NWG, doesn't support default events handler.

**Comment by zoumi** [comment]
There shoud be an envent manager. If users or builtin controls want to handle the envent, they need to regiester handle func to the manager. And the manager should determine to convey the even to next handler or just break the procedure according to the return value of handle func.

**Comment by zoumi** [comment]
![image](https://user-images.githubusercontent.com/5162901/30811031-898f5694-a239-11e7-9a2e-090cba8ff8f4.png)
Failed...
The problem is SysHeader321 send a bunch of WM_NOTIFY::NM_CUSTOMDRAW to SysListView321.

**Comment by gabdube** [comment]
If you want to have default event handler in NWG, you have to filter the event in the window procdure by introducing a subclass hook (see `hook_window_events` in `low/events`) or wrap the builtin control in a custom window (like I've done for the `TabView` control).

**Comment by gabdube** [comment]
Ok so I just pushed the base of the listview on the dev branch. There's nothing substantial yet though.

I'm closing this. Lets continue the discussion on #31
