### ISSUE TITLE
nwg_combobox macro with data=... does not work

### ISSUE THREAD

**Issue by ghost** [gabdube/native-windows-gui#54]
Using `nwg_combobox` with `data=...` will cause two compiler errors, E0243 and E0308.  E0243 appears to be caused by the macro giving `ComboBoxT` one type parameter (data) when it needs three, and E0308 appears to be caused by the macro assigning `[]` to the `collection` field of `ComboBoxT`.  On a side note, thanks for making this crate, it's really useful!

**Comment by gabdube** [comment]
Macros are now replaced by  builder and native-windows-derive. This fix this problem
