### ISSUE TITLE
Support for Common Dialog Box Functions?

### ISSUE THREAD

**Issue by minstrel271** [gabdube/native-windows-gui#55]
[https://msdn.microsoft.com/en-us/library/windows/desktop/ff468808(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/ff468808(v=vs.85).aspx)

**Comment by gabdube** [comment]
FileDialog, ColorDialog, and FontDialog implemented in 1.0 .  Other dialog won't be implemented unless someone requires them.
