### ISSUE TITLE
Problem with macros

### ISSUE THREAD

**Issue by winks** [gabdube/native-windows-gui#56]
Ok, I have a "minimal" repro case here: https://gist.github.com/winks/a65d5f6661718803305b71f12c373230

I started with the showcase example and stripped it down, this works (as it is pasted above).

If you uncomment lines 7,10,34 and run `cargo run` or `cargo build`: 
```
λ cargo build
   Compiling nw2 v0.1.0 (file:///C:/Users/Florian/code/winks/WastedTime/nw2)
error[E0244]: wrong number of type arguments: expected 0, found 2
  --> src/main.rs:12:1
   |
12 | / nwg_template!(
13 | |     head: setup_ui<&'static str>,
14 | |     controls: [
15 | |         ("MainWindow", nwg_window!(title="WastedTime"; position=(100, 100); size=(300, 50))),
...  |
52 | |     values: []
53 | | );
   | |__^ expected no type arguments
   |
   = note: this error originates in a macro outside of the current crate

error: aborting due to previous error(s)

error: Could not compile `nw2`.

To learn more, run the command again with --verbose.
```

I tried everything from `#[macro_use(json, json_internal)]` for `serde_json` to `#[macro_use(nwg_template, ...)]` for `native-windows-gui` to all combinations I can think of - as soon as I have a second `macro_use` I can't compile anymore.
I originally had everything in one file as well, but tried to split it out to get a better on/off - no change

**Comment by gabdube** [comment]
I will look into this.

**Comment by winks** [comment]
Happy to help in any way, this is my only blocker (and my macro-fu is too weak), enjoying the rest of the library very much so far :+1:

**Comment by gabdube** [comment]
Sorry for the delay. The problem comes from `Result` type imported from your `wasted`. The nwg_template returns a `Result<(), $crate::Error>` type and the new type breaks this. 

So either renaming the new `Error` type to something else or wrapping the nwg_template macro in a `module{}` should do the trick.

**Comment by winks** [comment]
Wow, thanks for the detective work and sorry for wasting your time. 
I failed to properly create a minimal reproduce case and really had 2 changes there, not one (my crate and serde) - but the error message was just too misleading.

Closing this.
