### ISSUE TITLE
How to dispatch event from another thread

### ISSUE THREAD

**Issue by joaomoreno** [gabdube/native-windows-gui#58]
I can't seem to figure out how to dispatch an event from a separate thread. I'm attempting to update a progress bar as a separate thread does some heavy work.

Any hints?

**Comment by fenhl** [comment]
I have a similar question. My app starts a loop that performs an hourly check, and I'm attempting to open a file dialog from within it. This currently seems to be impossible since `Ui` isn't `Send`.

**Comment by gabdube** [comment]
1.0 now has a notice control to wake up the GUI thread from a separate thread.
