### ISSUE TITLE
Events of CheckBox & RadioButton seem not working

### ISSUE THREAD

**Issue by foresthan** [gabdube/native-windows-gui#61]
I added the following piece in the events section of the showcase example to test the events of checkbox and radiobutton. Only Event::Raw was triggered while other events, such as Click, DoubleClick, etc. did not work. Do I miss anything here? 

(PS. The buttons, menu items and textbox are working well with all other event types in addition to Raw.)

events: [
... ...

       ("CatRadio", "SelectCat", Event::Click, |_,_,_,_| {
            nwg::simple_message("Cat", "Hello Cat!");
        }),

        ("HappyCheckBox", "CheckHappy", Event::DoubleClick, |_,_,_,_| {
            nwg::simple_message("Happy", "Hello check happy!");
        }),

        ("TriCheckBox", "CheckTribox", Event::Focus, |_,_,_,_| {
            nwg::simple_message("TriState", "Hello tristate box!");
        }),

        ("YesRadio", "SelectYes", Event::Click, |_,_,_,_| {
            nwg::simple_message("Yes", "Selected Yes!");
        }),

... ...
];

**Comment by gabdube** [comment]
I think this is because the events were not always dispatched correctly in `0.2.0`. This might be fixed in the `dev` branch. But the project is dead, so yeah...

**Comment by Shcak** [comment]
Similar problem : 

     #[macro_use] extern crate native_windows_gui as nwg;
     use nwg::{Ui, Event, simple_message};
     
     nwg_template!(
         head: setup_ui<&'static str>,
         controls: [
             ("MainWindow", nwg_window!(
                     title="Example";
                     size=(200,70) )),
             ("ComboBox", nwg_combobox!( parent="MainWindow";
                     placeholder=Some("Choose".to_string());
                     collection=vec!["Choice".to_string(), "Another".to_string()];
                     position=(5,5); size=(190,30) )),
             ("Button", nwg_button!( parent="MainWindow";
                     text="Click";
                     position=(5,35); size=(190,30) ))
         ];
         events: [
             ("ComboBox", "Choose", Event::SelectionChanged, |_,_,_,_| {
                 simple_message("Question", "Why this never displays?");
             }),
             ("Button", "Click", Event::Click, |_,_,_,_| {
                 simple_message("Thit works", "But this does?");
             })
         ];
         resources: [];
         values: []
     );
     
     fn create_ui() -> Result<Ui<&'static str>, nwg::Error> {
         let ui: Ui<&'static str>;
     
         match Ui::new() {
             Ok(_ui) => { ui = _ui; },
             Err(e) => { return Err(e) }
         }
     
         if let Err(e) = setup_ui(&ui) {
             Err(e)
         } else {
             Ok(ui)
         }
     }
     
     fn main() {
         let _ui = create_ui().expect("Failed to initialize GUI");
         nwg::dispatch_events();
     }


The `Event::Click` event works but the `Event::SelectionChanged` never triggers.

Is it completely dead ?
I just spent a couple of days learning to use it...

**Comment by gabdube** [comment]
Fixed in 1.0
