### ISSUE TITLE
Document page of "Macro native_windows_gui::nwg_combobox" is incorrect

### ISSUE THREAD

**Issue by foresthan** [gabdube/native-windows-gui#62]
In the document of "Macro native_windows_gui::nwg_combobox" (https://gabdube.github.io/native-windows-gui/api/native_windows_gui/macro.nwg_combobox.html), the usage examples are incorrect. 

Instead of nwg_combobox!(data=String; parent="MyParent";), it should be nwg_combobox!(data=String, parent="MyParent";)  -- it has to be comma, instead of semicolon to pass compiling.

In addition, even using comma after data parameter, I still got error in codes: 
(MySelector, nwg_combobox!(data=String, parent=MainWindow; position=(175, 25); size=(130, 30) 
)),
^ expected 3 type arguments
expected struct `std::vec::Vec`, found array of 0 elements
help: try using a conversion method: `[  ].to_vec()`

Which type argument was missed here?

**Comment by gabdube** [comment]
Dup of https://github.com/gabdube/native-windows-gui/issues/55

This error exists because the data initialization for the combobox was not done correctly.
