### ISSUE TITLE
Document event types

### ISSUE THREAD

**Issue by fenhl** [gabdube/native-windows-gui#66]
Some of the [event types](https://gabdube.github.io/native-windows-gui/api/native_windows_gui/enum.Event.html) are not clear at all:

* `Char`
* `Paint`
* `Raw`
* `ValueChanged`
* `LimitReached`
* `Tick`
* `Triggered`

I'm currently trying to run some code when the main window is first created, and the answer is probably in here somewhere but I can't tell because it's undocumented. Some form of documentation about when these events fire would be helpful.

**Comment by gabdube** [comment]
No longer applies. Events in 1.0 are all documented and each control list their events
