### ISSUE TITLE
Link shell32.dll explicitly

### ISSUE THREAD

**Issue by foresthan** [gabdube/native-windows-gui#68]
Since Dec 2018, RLS removed the implicit dependency on shell32.dll. As a result, native-windows-gui failed to build on new RLS builds, either stable or nightly. The explicit linking to shell32.dll is required.

**Comment by gabdube** [comment]
I will look into this.

**Comment by gabdube** [comment]
Heads up. I linked shell32 in the build script and it fix the build. That said, I want to wait a bit more before publishing the fix because of this issue: https://github.com/gabdube/native-windows-gui/issues/69

I will close this when the fixed version will be on crates.io

**Comment by gabdube** [comment]
Fixed. Use `native-windows-gui = "0.2.1"` in Cargo.toml
