### ISSUE TITLE
Fails to run on Rust 1.34.1.

### ISSUE THREAD

**Issue by IslandUsurper** [gabdube/native-windows-gui#69]
While my code worked on Rust 1.32.0 (stable), upgrading to 1.34.1 caused the following error:

    thread 'main' panicked at 'Failed to find a control: They key exists in the Ui, but the type requested did not match the type of the underlying object', src\libcore\result.rs:997:5

Setting `$env:RUST_BACKTRACE=1` only reveals an empty backtrace.

I did try running `cargo update` to get the latest version of all my dependencies, but that didn't help either.

**Comment by gabdube** [comment]
Renaming `ResourceT::type_id` to something else fix the problem.

**Comment by gabdube** [comment]
Fixed. Use `native-windows-gui = "0.2.1"` in Cargo.toml
