### ISSUE TITLE
BoxLayout should be able to have independent sizes for each of its children

### ISSUE THREAD

**Issue by ivanceras** [gabdube/native-windows-gui#70]
https://github.com/gabdube/native-windows-gui/blob/1.0-prerelease/native-windows-gui/src/layouts/box_layout.rs#L237

```rust
            let local_width = (_item_width * item.span) + (sp2 * (item.span - 1));
            let local_height = (_item_height * item.span) + (sp2 * (item.span - 1));
```
My understand is that Box (such as in Gtk) should be able to accommodate the  children content independent on the size of the cells.
It looks like the BoxLayout in nwg is implemented in the assumption that the cells must have the same sizes.

Is this something we could change the behavior of BoxLayout or is there an alternative control should I be using instead.

**Comment by gabdube** [comment]
Right now the code for the layouts is ultra simple. It really just split the parent space in equal parts. I think it should be a good idea to implement this before the release. I think adding a "preserve_item_size" option in the BoxLayout and then update the `update_layout` should do the trick.

**Comment by ivanceras** [comment]
I've found this [crate](https://github.com/vislyhq/stretch) for computing the sizes of children components in a flex container, this maybe useful for calculating the boxlayout allocation of the children. I will be also using this for the [TUI backend of sauron-native](https://github.com/ivanceras/itui)

**Comment by gabdube** [comment]
Nice find! I'll look into it tomorrow. If it works fine, I will probably implement it this weekend

**Comment by gabdube** [comment]
Just pushed a small example at `cargo run --example flexbox` . Works great. NWG will have a new `FlexboxLayout` which will probably replace BoxLayout. GridLayout will stay like it is.

**Comment by ivanceras** [comment]
Hi gab, I just tested the FlexboxLayout and it looks good.

**Comment by gabdube** [comment]
Closed as BoxLayout was now fully replaced by FlexboxLayout. Working on https://github.com/gabdube/native-windows-gui/issues/72 next
