### ISSUE TITLE
STATUS_ENTRYPOINT_NOT_FOUND when trying to run example

### ISSUE THREAD

**Issue by flaghacker** [gabdube/native-windows-gui#78]
I'm trying to run the examples of the current 1.0-prerelease branch, and I did as the README says:

```
git clone https://github.com/gabdube/native-windows-gui.git
cd native-windows-gui/native-windows-gui
cargo run --example calculator
```

And I get the following error:

```
process didn't exit successfully: `C:\Users\Karel\Desktop\native-windows-gui\target\debug\examples\calculator.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
```

I also get the same error when running the test suite. From looking around online it looks like this means there is some DLL missing, but which one?

**Comment by gabdube** [comment]
NWG only uses Windows DLL but it was only tested on the lastest version of Windows 10 so I might be using some functions that are not available on older versions of Windows or only on the MSVC toolchain.

That said, Calculator only depends on the most basic features of NWG so there's not many things that can go wrong (yay).

So questions:
 - What version of Windows a you currently using
 - What toolchain are you currently using (MSVC, GNU)
- Maybe try to run the example without styling (`cargo run --example calculator --features "no-styling"`)

**Comment by flaghacker** [comment]
- I'm also running Windows 10, version 2004 OS Build 19041.208, and I updated just yesterday.
- I was running GNU, but now I've tried it on MSVC (both version 1.41.0) and that does work. Am I just supposed to use MSVC instead?
- Without styling I still get the same error

**Comment by flaghacker** [comment]
Ah yes, the README specifically says 
> **NWG will not compile on the GNU toolchain.**
I missed that.

**Comment by gabdube** [comment]
Yeah GNU is missing some functions. It might be possible to workaround them, but I haven't looked into that yet.

**Comment by gabdube** [comment]
Added the warning in the lastest readme
