### ISSUE TITLE
Test app: crash when closing Controls window and interacting with "Action panel"

### ISSUE THREAD

**Issue by nyanpasu64** [gabdube/native-windows-gui#79]
- `git checkout 1.0-prerelease`
- `cargo test --features all`
- Click "Control tests" button
- Close "Controls" window
- Click any button in "Action panel" window (specifically "Run window test")

The app crashes. Trying to debug in lldb makes lldb crash. Trying to debug in windbg preview reveals one of the assertions failed, but instead of a graceful shutdown, the app crashes. Is this a bug?

windbg preview reports that `native_windows_gui_3b423072d1484df6!panic_unwind::imp::panic + 0x71` crashes with codes `c000001d` (ud2 instruction) and `c000041d`.

The `cargo test` executable reports "(exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)".

----

I just realized that "Action panel" is intended to mutate the "Controls" window. And if you close the Controls window, there's an assertion error.

To bring the test app back to a usable state, click "Control tests" again.

**Comment by gabdube** [comment]
Adding an event that close the action panel when the control window will fix this problem.

**Comment by gabdube** [comment]
Fixed
