### ISSUE TITLE
Changes to bind_raw_event_handler

### ISSUE THREAD

**Issue by Mazwak** [gabdube/native-windows-gui#83]
Hello

I use bind_raw_event_handler to set a minimum size. Once it worked, I looked at the source for the function, and I would like to discuss 2 points :

 ## Changing the handler_id

You change the handler_id provided by the user by adding 0xFFFF.

At the very least, I would use a saturating_add to avoid runtime crash, and document it.

However, I think it would be better to just not accept values < 0xFFFF.

At the moment, a user might reuse the id he provided to unbound the event, and not the one returned, thinking they are the same.

## panic or Result

I'm not sure about this one, but I feel like the function should return a result instead of panicking.

From source, it seems you do use a lot of Result, and not much panic!, so maybe it's just an oversight.

What do you think about all this ?

**Comment by gabdube** [comment]
> However, I think it would be better to just not accept values < 0xFFFF

I agree. That just make more sense.

> I'm not sure about this one, but I feel like the function should return a result instead of panicking

Passing a bad handle (ie a menu) to the function should panic. That's what is used everywhere else. That said, the "There is already a raw event handler bound with the handler ID" should be a result. And using a bad ID could become a `compile_error`

So yeah, those are pretty good ideas. I'll try to implement them as soon as possible. So later today or later this week.

**Comment by gabdube** [comment]
Added a new error type `NwgError::EventsBinding` for errors related to the handler binding. `bind_raw_event_handler ` now panics if the handler_id is smaller than 0xffff. `bind_raw_event_handler_inner` is now used internally to skip the id check.

**Comment by Mazwak** [comment]
Thanks
