### ISSUE TITLE
Expand macro documentation

### ISSUE THREAD

**Issue by danielrangelmoreira** [gabdube/native-windows-gui#85]
![image](https://user-images.githubusercontent.com/788347/82735432-19639300-9cf8-11ea-875e-52535b4e36ea.png)
`cargo doc -p native-windows-derive` give me this sparse material, I had to rely on examples.

**Comment by gabdube** [comment]
The derive macros are covered in details in the docs https://github.com/gabdube/native-windows-gui/tree/1.0-prerelease/native-windows-docs . See `nwd_*.html`. That's said there should at least a high level overview here. I'll work on this right away. Thanks.

**Comment by gabdube** [comment]
Done. Tell me if you think I missed something.
