### ISSUE TITLE
[Discussion] Add a way to set min size

### ISSUE THREAD

**Issue by Mazwak** [gabdube/native-windows-gui#86]
Hello

I managed to set a minimum window size using raw_bind and WinAPI MinMaxInfo.

I then looked how to integrate it to nwg, but it needs state to remember the event handler, and at the moment, Window only has a ControlHandle.

You need state to remember which event you bound to MINMAXINFO, and to unbind it if you were to change the min size.

The first thing that would be nice would be to add it to WindowBuilder. You would not be allowed to change it afterward, but you could at least specify it at creation.

The second thing would be to allow to modify it, but then, state is needed to unbind the event, and rebind it with the new min size. There are various solutions to this problem, but I'm not sure it should be added. There isn't a lot of use case.

Do you think you want the first point ? I can work on a PR.

**Comment by gabdube** [comment]
Your first point make sense. Go for it!

Also it's technically ok to add handlers to controls. For example in `TextInput`, there's a `handler0: RefCell<Option<RawEventHandler>>,` for the size fix. The same can be done for Window.

**Comment by gabdube** [comment]
I've implemented this feature using an event instead. See this example: https://github.com/gabdube/native-windows-gui/blob/master/native-windows-gui/examples/min_max_size_d.rs

**Comment by Mazwak** [comment]
Thanks.

Sorry I couldn't provide anything.
