### ISSUE TITLE
some heap corruptions in certain functions, supplied text buffer too small

### ISSUE THREAD

**Issue by Tobi34** [gabdube/native-windows-gui#87]
I have tried out 1.0-preview. Doing this i ran into a heap corruption. I did a little review and here is the result:

In ComboBox::selection_string a string size is requested and when the string is fetched the buffer is one byte to small. 
From Microsoft Documentation:
CB_GETLBTEXTLEN: "The return value is the length of the string, in TCHARs, excluding the terminating null character"
CB_GETLBTEXT: "A pointer to the buffer that receives the string. The buffer must have sufficient space for the string and a terminating null character."

The same seems to be true for ListBox::selection_string                                                                                                       
LB_GETTEXTLEN  "The return value is the length of the string, in TCHARs, excluding the terminating null character. "
LB_GETTEXT  "The buffer must have sufficient space for the string and a terminating null character."

The same seems to be true for StatusBar::text.
SB_GETTEXTLENGTHW: "The low word specifies the length, in characters, of the text."
SB_GETTEXTW: "Pointer to the buffer that receives the text as a null-terminated string."

(This is my very first interaction in github, so I hope I did nothing wrong.)

**Comment by gabdube** [comment]
Thank you, I'll work on this next. Also good job on your first issue, you've described the problem and offered a solution. This is the best way to do it.

**Comment by gabdube** [comment]
Added an extra wchar of space for the null character in the linked methods. I wasn't able to replicate the heap corruption with the current code, but using a buffer that was way too small on purpose generated heap corruption crash pretty quickly.
