### ISSUE TITLE
Question: How much size does this crate add if added as a dependency?

### ISSUE THREAD

**Issue by heinrich5991** [gabdube/native-windows-gui#89]

**Comment by gabdube** [comment]
Depends how many features you use. 

On my computer, the default "print hello world" project is 145 kb. The basic gui example is 180 kb and most examples are between 180 and 200 kb. The test suite, which uses all features and has lots of GUI logic is 1mb. 

So I'd say 40kb for the built-in features and 5 to 10 kb for every additional features.
