### ISSUE TITLE
Progress Bar missing marquee support

### ISSUE THREAD

**Issue by AmionSky** [gabdube/native-windows-gui#90]
https://docs.microsoft.com/en-us/windows/win32/controls/pbm-setmarquee

My implementation for it:
https://github.com/AmionSky/native-windows-gui/blob/pb-styles/native-windows-gui/src/controls/progress_bar.rs

**Comment by gabdube** [comment]
Looks good. The builder parameter should take only one parameter so that it works nicely with the derive macro. I'll add the feature on my side.

**Comment by gabdube** [comment]
Added the feature. The builder implementation is a bit different from yours. I separated the builder method `marquee` in two. `marquee` to enable the animation and `marquee_update` for the animation speed.
