### ISSUE TITLE
Clipboard improvements (integrate clipboard-win?)

### ISSUE THREAD

**Issue by DoumanAsh** [gabdube/native-windows-gui#93]
There are few aspects that you can improve in clipboard:

- Use `IsClipboardFormatAvailable` to determine if format is available which can be used without clipboard open
- Check for failure `SetClipboardData` - if it fails you need to free memory
- Use `MultiByteToWideChar` to efficiently write encoded string onto allocated memory instead of using intermediate allocation (and then append 0)

You can use my code in `clipboard-win` as reference if you want something more

**Comment by gabdube** [comment]
Looks good! Will merge after testing.

**Comment by DoumanAsh** [comment]
@gabdube Do you want me to add `MultiByteToWideChar` part? It will basically make text setter specialized version of clipboard data set as it will have to allocate data by itself and set it

**Comment by gabdube** [comment]
Not sure. Is there a benefit over just using my "to_utf16"?

**Comment by DoumanAsh** [comment]
You avoid intermediate allocation of `Vec<u16>` as `MultiByteToWideChar` allows to return required size of buffer.

**Comment by DoumanAsh** [comment]
See how I implement string setting https://github.com/DoumanAsh/clipboard-win/blob/master/src/raw.rs#L320-L348

**Comment by gabdube** [comment]
Ok go for it.

**Comment by gabdube** [comment]
Might just be a better idea to use your library under the hood though. I like the "get_file_list" and "get_bitmap". Also you have a typo in "set_bitamp"

**Comment by DoumanAsh** [comment]
lol, I didn't notice,  but I already stabilized API too late for rename :D

If you consider my library ok dependency then yeah it would be better to use it than copy-pasting code from it :)

**Comment by gabdube** [comment]
Ok so add `MultiByteToWideChar` for now and I'll merge it today. I will look into integrating your library later

**Comment by gabdube** [comment]
Tested and works perfectly. Merged. I'll leave this issue open to remind me about the integration

**Comment by gabdube** [comment]
I decided not to do this. Instead I added links to your library in the docs if the users wants to use a more robust API
