### ISSUE TITLE
Set styles on controls after creation

### ISSUE THREAD

**Issue by AmionSky** [gabdube/native-windows-gui#97]
I need this functionality to turn marquee on the progress bar on/off.

I wrote this to fix my issue:
https://github.com/AmionSky/native-windows-gui/blob/9876ee5466a352fdb4547220a1b2b4b8771f34c5/native-windows-gui/src/controls/progress_bar.rs#L207-L227

**Comment by gabdube** [comment]
Make sense. You can use `wh::get_style` and `wh::set_style`.  Will make a commit right now

**Comment by gabdube** [comment]
Commited. I decided to use `remove_flags` and `add_flags` because we update "ProgressBarFlags".
