### ISSUE TITLE
syncdraw crashes at startup

### ISSUE THREAD

**Issue by mark-summerfield** [gabdube/native-windows-gui#98]
I downloaded the `.zip` of NWG and tried all the examples and they all worked fine.
However, when I tried `syncdraw` it crashed:
```
   Compiling syncdraw v0.1.0 (C:\tmp\native-windows-gui-master\native-windows-gui\examples\sync-draw)
    Finished dev [unoptimized + debuginfo] target(s) in 21.86s
     Running `C:\tmp\native-windows-gui-master\target\debug\syncdraw.exe`
error: process didn't exit successfully: `C:\tmp\native-windows-gui-master\target\debug\syncdraw.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```
I do all my testing in Windows 7-64 inside a VirtualBox so it could be a problem with VirtualBox.

**Comment by gabdube** [comment]
On top of NWG, syncdraw use shared memory, win32 events, and opengl 4.3. Because of the VM I think opengl 4.3 is probably the reason why it crashes. You can try to strip away `opengl_canvas` and see if it works.

**Comment by gabdube** [comment]
Lets assume it's a VM problem
